import sqlite from "@prisma/orm-sqlite/runtime";
import type { Contract } from "@/prisma/contract";
import contractJson from "@/prisma/contract.json";

// Prisma 8 client. `contract.json` / `contract.d.ts` are generated by
// `prisma contract emit` from src/prisma/contract.prisma — never edit them.
// SQLite has no schemas, so models are addressed as `db.orm.<Model>`.
function createDb() {
  return sqlite<Contract>({
    contractJson,
    path: process.env.SQLITE_PATH ?? "./db/reroute.db",
  });
}

// Singleton — survives Next.js dev-server hot reloads without opening a new
// SQLite handle on every module reload.
const globalForDb = globalThis as unknown as {
  db?: ReturnType<typeof createDb>;
};

// Ids are generated here because the SQLite contract cannot declare an id
// default (see the note in contract.prisma).
export const newId = (): string => crypto.randomUUID();

export const db = globalForDb.db ?? createDb();

if (process.env.NODE_ENV !== "production") globalForDb.db = db;
