import postgres from "@prisma/orm-postgres/runtime";
import type { Contract } from "@/prisma/contract";
import contractJson from "@/prisma/contract.json";

// Prisma 8 client for PostgreSQL. `contract.json` / `contract.d.ts` are
// generated by `prisma contract emit` from src/prisma/contract.prisma — never
// edit them. Models live in the `public` schema: `db.orm.public.<Model>`.
//
// DATABASE_URL: use the POOLED connection string in production (serverless
// functions open many short-lived connections); the direct string is for
// migrations only. The client connects lazily, on the first query.
function createDb() {
  return postgres<Contract>({
    contractJson,
    url: process.env.DATABASE_URL,
  });
}

// Singleton — survives Next.js dev-server hot reloads without opening a new
// connection pool on every module reload.
const globalForDb = globalThis as unknown as {
  db?: ReturnType<typeof createDb>;
};

// Ids are generated here because the contract cannot declare an id default
// (see the note in contract.prisma).
export const newId = (): string => crypto.randomUUID();

/** ISO-8601 UTC timestamp for the text timestamp columns. */
export const nowIso = (): string => new Date().toISOString();

export const db = globalForDb.db ?? createDb();

if (process.env.NODE_ENV !== "production") globalForDb.db = db;
