// ⚠️  GENERATED FILE - DO NOT EDIT
// This file is automatically generated by 'prisma contract emit'.
// To regenerate, run: prisma contract emit
import type { CodecTypes as SqliteTypes } from '@prisma/orm-sqlite/adapter/codec-types';

import type {
  ContractWithTypeMaps,
  RelationKeys,
  TypeMaps as TypeMapsType,
} from '@prisma/orm-sqlite/family-contract/types';
import type {
  Contract as ContractType,
  ExecutionHashBase,
  NamespaceId,
  ProfileHashBase,
  StorageHashBase,
} from '@prisma/orm-sqlite/contract/types';

export type StorageHash =
  StorageHashBase<'855666c61b92820aebdb9af4ff8138123d7e624b999d6c4bf38a3e5987fb865c'>;
export type ExecutionHash = ExecutionHashBase<string>;
export type ProfileHash =
  ProfileHashBase<'260b8608d1aacaf1f690779a6cff39a12947c599597c5ba464ca75b9e775df53'>;

export type CodecTypes = SqliteTypes;
export type LaneCodecTypes = CodecTypes;
export type QueryOperationTypes = Record<string, never>;
export type AggregateTypes = {
  readonly avg: {
    readonly byCodec: {
      readonly 'sql/float@1': { readonly output: 'sqlite/real@1'; readonly nullable: true };
      readonly 'sql/int@1': { readonly output: 'sqlite/real@1'; readonly nullable: true };
      readonly 'sqlite/bigint@1': { readonly output: 'sqlite/real@1'; readonly nullable: true };
      readonly 'sqlite/bigintnumber@1': {
        readonly output: 'sqlite/real@1';
        readonly nullable: true;
      };
      readonly 'sqlite/integer@1': { readonly output: 'sqlite/real@1'; readonly nullable: true };
      readonly 'sqlite/real@1': { readonly output: 'sqlite/real@1'; readonly nullable: true };
    };
  };
  readonly count: {
    readonly byCodec: {};
    readonly withoutInput: { readonly output: 'sqlite/bigintnumber@1'; readonly nullable: false };
    readonly anyInput: { readonly output: 'sqlite/bigintnumber@1'; readonly nullable: false };
  };
  readonly countBigInt: {
    readonly byCodec: {};
    readonly withoutInput: { readonly output: 'sqlite/bigint@1'; readonly nullable: false };
    readonly anyInput: { readonly output: 'sqlite/bigint@1'; readonly nullable: false };
  };
  readonly max: {
    readonly byCodec: {
      readonly 'sql/float@1': { readonly output: 'sql/float@1'; readonly nullable: true };
      readonly 'sql/int@1': { readonly output: 'sql/int@1'; readonly nullable: true };
      readonly 'sqlite/bigint@1': { readonly output: 'sqlite/bigint@1'; readonly nullable: true };
      readonly 'sqlite/bigintnumber@1': {
        readonly output: 'sqlite/bigintnumber@1';
        readonly nullable: true;
      };
      readonly 'sqlite/blob@1': { readonly output: 'sqlite/blob@1'; readonly nullable: true };
      readonly 'sqlite/datetime@1': {
        readonly output: 'sqlite/datetime@1';
        readonly nullable: true;
      };
      readonly 'sqlite/integer@1': { readonly output: 'sqlite/integer@1'; readonly nullable: true };
      readonly 'sqlite/json@1': { readonly output: 'sqlite/json@1'; readonly nullable: true };
      readonly 'sqlite/real@1': { readonly output: 'sqlite/real@1'; readonly nullable: true };
      readonly 'sqlite/text@1': { readonly output: 'sqlite/text@1'; readonly nullable: true };
    };
  };
  readonly min: {
    readonly byCodec: {
      readonly 'sql/float@1': { readonly output: 'sql/float@1'; readonly nullable: true };
      readonly 'sql/int@1': { readonly output: 'sql/int@1'; readonly nullable: true };
      readonly 'sqlite/bigint@1': { readonly output: 'sqlite/bigint@1'; readonly nullable: true };
      readonly 'sqlite/bigintnumber@1': {
        readonly output: 'sqlite/bigintnumber@1';
        readonly nullable: true;
      };
      readonly 'sqlite/blob@1': { readonly output: 'sqlite/blob@1'; readonly nullable: true };
      readonly 'sqlite/datetime@1': {
        readonly output: 'sqlite/datetime@1';
        readonly nullable: true;
      };
      readonly 'sqlite/integer@1': { readonly output: 'sqlite/integer@1'; readonly nullable: true };
      readonly 'sqlite/json@1': { readonly output: 'sqlite/json@1'; readonly nullable: true };
      readonly 'sqlite/real@1': { readonly output: 'sqlite/real@1'; readonly nullable: true };
      readonly 'sqlite/text@1': { readonly output: 'sqlite/text@1'; readonly nullable: true };
    };
  };
  readonly sum: {
    readonly byCodec: {
      readonly 'sql/float@1': { readonly output: 'sqlite/real@1'; readonly nullable: true };
      readonly 'sql/int@1': { readonly output: 'sqlite/bigintnumber@1'; readonly nullable: true };
      readonly 'sqlite/bigint@1': {
        readonly output: 'sqlite/bigintnumber@1';
        readonly nullable: true;
      };
      readonly 'sqlite/bigintnumber@1': {
        readonly output: 'sqlite/bigintnumber@1';
        readonly nullable: true;
      };
      readonly 'sqlite/integer@1': {
        readonly output: 'sqlite/bigintnumber@1';
        readonly nullable: true;
      };
      readonly 'sqlite/real@1': { readonly output: 'sqlite/real@1'; readonly nullable: true };
    };
  };
  readonly sumBigInt: {
    readonly byCodec: {
      readonly 'sql/int@1': { readonly output: 'sqlite/bigint@1'; readonly nullable: true };
      readonly 'sqlite/bigint@1': { readonly output: 'sqlite/bigint@1'; readonly nullable: true };
      readonly 'sqlite/bigintnumber@1': {
        readonly output: 'sqlite/bigint@1';
        readonly nullable: true;
      };
      readonly 'sqlite/integer@1': { readonly output: 'sqlite/bigint@1'; readonly nullable: true };
    };
  };
};
type DefaultLiteralValue<CodecId extends string, Encoded> = CodecId extends keyof CodecTypes
  ? Encoded extends CodecTypes[CodecId]['json']
    ? Encoded
    : CodecTypes[CodecId]['json']
  : Encoded;

export type FieldOutputTypes = {
  readonly __unbound__: {
    readonly Attempt: {
      readonly id: CodecTypes['sqlite/text@1']['output'];
      readonly studentId: CodecTypes['sqlite/text@1']['output'];
      readonly questionId: CodecTypes['sqlite/text@1']['output'];
      readonly diagnosticId: CodecTypes['sqlite/text@1']['output'];
      readonly selectedOption: CodecTypes['sqlite/text@1']['output'];
      readonly correct: CodecTypes['sqlite/integer@1']['output'];
      readonly responseTimeSeconds: CodecTypes['sqlite/integer@1']['output'];
      readonly inferredConfidence: CodecTypes['sqlite/text@1']['output'];
      readonly inferredMasterySignal: CodecTypes['sqlite/text@1']['output'];
      readonly telemetryJson: CodecTypes['sqlite/text@1']['output'];
      readonly createdAt: CodecTypes['sqlite/datetime@1']['output'];
    };
    readonly DiagnosticSession: {
      readonly id: CodecTypes['sqlite/text@1']['output'];
      readonly studentId: CodecTypes['sqlite/text@1']['output'];
      readonly subject: CodecTypes['sqlite/text@1']['output'];
      readonly createdAt: CodecTypes['sqlite/datetime@1']['output'];
      readonly completedAt: CodecTypes['sqlite/datetime@1']['output'] | null;
    };
    readonly Intervention: {
      readonly id: CodecTypes['sqlite/text@1']['output'];
      readonly studentId: CodecTypes['sqlite/text@1']['output'];
      readonly topic: CodecTypes['sqlite/text@1']['output'];
      readonly actionType: CodecTypes['sqlite/text@1']['output'];
      readonly contentJson: CodecTypes['sqlite/text@1']['output'];
      readonly startedAt: CodecTypes['sqlite/datetime@1']['output'];
      readonly completedAt: CodecTypes['sqlite/datetime@1']['output'] | null;
      readonly masteryBefore: CodecTypes['sqlite/real@1']['output'];
      readonly masteryAfter: CodecTypes['sqlite/real@1']['output'] | null;
      readonly improved: CodecTypes['sqlite/integer@1']['output'] | null;
    };
    readonly LearnerProfile: {
      readonly id: CodecTypes['sqlite/text@1']['output'];
      readonly studentId: CodecTypes['sqlite/text@1']['output'];
      readonly overallJson: CodecTypes['sqlite/text@1']['output'];
      readonly byTopicJson: CodecTypes['sqlite/text@1']['output'];
      readonly readinessIndex: CodecTypes['sqlite/integer@1']['output'];
      readonly profileConfidence: CodecTypes['sqlite/real@1']['output'];
      readonly updatedAt: CodecTypes['sqlite/datetime@1']['output'];
    };
    readonly Question: {
      readonly id: CodecTypes['sqlite/text@1']['output'];
      readonly subject: CodecTypes['sqlite/text@1']['output'];
      readonly topic: CodecTypes['sqlite/text@1']['output'];
      readonly subtopic: CodecTypes['sqlite/text@1']['output'];
      readonly concept: CodecTypes['sqlite/text@1']['output'];
      readonly difficulty: CodecTypes['sqlite/text@1']['output'];
      readonly estimatedTimeSeconds: CodecTypes['sqlite/integer@1']['output'];
      readonly questionText: CodecTypes['sqlite/text@1']['output'];
      readonly optionsJson: CodecTypes['sqlite/text@1']['output'];
      readonly correctOption: CodecTypes['sqlite/text@1']['output'];
      readonly distractorsJson: CodecTypes['sqlite/text@1']['output'];
      readonly explanation: CodecTypes['sqlite/text@1']['output'];
    };
    readonly Student: {
      readonly id: CodecTypes['sqlite/text@1']['output'];
      readonly name: CodecTypes['sqlite/text@1']['output'] | null;
      readonly targetExam: CodecTypes['sqlite/text@1']['output'];
      readonly targetScore: CodecTypes['sqlite/integer@1']['output'];
      readonly subjects: CodecTypes['sqlite/text@1']['output'];
      readonly createdAt: CodecTypes['sqlite/datetime@1']['output'];
    };
  };
};
export type FieldInputTypes = {
  readonly __unbound__: {
    readonly Attempt: {
      readonly id: CodecTypes['sqlite/text@1']['input'];
      readonly studentId: CodecTypes['sqlite/text@1']['input'];
      readonly questionId: CodecTypes['sqlite/text@1']['input'];
      readonly diagnosticId: CodecTypes['sqlite/text@1']['input'];
      readonly selectedOption: CodecTypes['sqlite/text@1']['input'];
      readonly correct: CodecTypes['sqlite/integer@1']['input'];
      readonly responseTimeSeconds: CodecTypes['sqlite/integer@1']['input'];
      readonly inferredConfidence: CodecTypes['sqlite/text@1']['input'];
      readonly inferredMasterySignal: CodecTypes['sqlite/text@1']['input'];
      readonly telemetryJson: CodecTypes['sqlite/text@1']['input'];
      readonly createdAt: CodecTypes['sqlite/datetime@1']['input'];
    };
    readonly DiagnosticSession: {
      readonly id: CodecTypes['sqlite/text@1']['input'];
      readonly studentId: CodecTypes['sqlite/text@1']['input'];
      readonly subject: CodecTypes['sqlite/text@1']['input'];
      readonly createdAt: CodecTypes['sqlite/datetime@1']['input'];
      readonly completedAt: CodecTypes['sqlite/datetime@1']['input'] | null;
    };
    readonly Intervention: {
      readonly id: CodecTypes['sqlite/text@1']['input'];
      readonly studentId: CodecTypes['sqlite/text@1']['input'];
      readonly topic: CodecTypes['sqlite/text@1']['input'];
      readonly actionType: CodecTypes['sqlite/text@1']['input'];
      readonly contentJson: CodecTypes['sqlite/text@1']['input'];
      readonly startedAt: CodecTypes['sqlite/datetime@1']['input'];
      readonly completedAt: CodecTypes['sqlite/datetime@1']['input'] | null;
      readonly masteryBefore: CodecTypes['sqlite/real@1']['input'];
      readonly masteryAfter: CodecTypes['sqlite/real@1']['input'] | null;
      readonly improved: CodecTypes['sqlite/integer@1']['input'] | null;
    };
    readonly LearnerProfile: {
      readonly id: CodecTypes['sqlite/text@1']['input'];
      readonly studentId: CodecTypes['sqlite/text@1']['input'];
      readonly overallJson: CodecTypes['sqlite/text@1']['input'];
      readonly byTopicJson: CodecTypes['sqlite/text@1']['input'];
      readonly readinessIndex: CodecTypes['sqlite/integer@1']['input'];
      readonly profileConfidence: CodecTypes['sqlite/real@1']['input'];
      readonly updatedAt: CodecTypes['sqlite/datetime@1']['input'];
    };
    readonly Question: {
      readonly id: CodecTypes['sqlite/text@1']['input'];
      readonly subject: CodecTypes['sqlite/text@1']['input'];
      readonly topic: CodecTypes['sqlite/text@1']['input'];
      readonly subtopic: CodecTypes['sqlite/text@1']['input'];
      readonly concept: CodecTypes['sqlite/text@1']['input'];
      readonly difficulty: CodecTypes['sqlite/text@1']['input'];
      readonly estimatedTimeSeconds: CodecTypes['sqlite/integer@1']['input'];
      readonly questionText: CodecTypes['sqlite/text@1']['input'];
      readonly optionsJson: CodecTypes['sqlite/text@1']['input'];
      readonly correctOption: CodecTypes['sqlite/text@1']['input'];
      readonly distractorsJson: CodecTypes['sqlite/text@1']['input'];
      readonly explanation: CodecTypes['sqlite/text@1']['input'];
    };
    readonly Student: {
      readonly id: CodecTypes['sqlite/text@1']['input'];
      readonly name: CodecTypes['sqlite/text@1']['input'] | null;
      readonly targetExam: CodecTypes['sqlite/text@1']['input'];
      readonly targetScore: CodecTypes['sqlite/integer@1']['input'];
      readonly subjects: CodecTypes['sqlite/text@1']['input'];
      readonly createdAt: CodecTypes['sqlite/datetime@1']['input'];
    };
  };
};
export type StorageColumnTypes = {
  readonly __unbound__: {
    readonly attempt: {
      readonly correct: CodecTypes['sqlite/integer@1']['output'];
      readonly createdAt: CodecTypes['sqlite/datetime@1']['output'];
      readonly diagnosticId: CodecTypes['sqlite/text@1']['output'];
      readonly id: CodecTypes['sqlite/text@1']['output'];
      readonly inferredConfidence: CodecTypes['sqlite/text@1']['output'];
      readonly inferredMasterySignal: CodecTypes['sqlite/text@1']['output'];
      readonly questionId: CodecTypes['sqlite/text@1']['output'];
      readonly responseTimeSeconds: CodecTypes['sqlite/integer@1']['output'];
      readonly selectedOption: CodecTypes['sqlite/text@1']['output'];
      readonly studentId: CodecTypes['sqlite/text@1']['output'];
      readonly telemetryJson: CodecTypes['sqlite/text@1']['output'];
    };
    readonly diagnosticSession: {
      readonly completedAt: CodecTypes['sqlite/datetime@1']['output'] | null;
      readonly createdAt: CodecTypes['sqlite/datetime@1']['output'];
      readonly id: CodecTypes['sqlite/text@1']['output'];
      readonly studentId: CodecTypes['sqlite/text@1']['output'];
      readonly subject: CodecTypes['sqlite/text@1']['output'];
    };
    readonly intervention: {
      readonly actionType: CodecTypes['sqlite/text@1']['output'];
      readonly completedAt: CodecTypes['sqlite/datetime@1']['output'] | null;
      readonly contentJson: CodecTypes['sqlite/text@1']['output'];
      readonly id: CodecTypes['sqlite/text@1']['output'];
      readonly improved: CodecTypes['sqlite/integer@1']['output'] | null;
      readonly masteryAfter: CodecTypes['sqlite/real@1']['output'] | null;
      readonly masteryBefore: CodecTypes['sqlite/real@1']['output'];
      readonly startedAt: CodecTypes['sqlite/datetime@1']['output'];
      readonly studentId: CodecTypes['sqlite/text@1']['output'];
      readonly topic: CodecTypes['sqlite/text@1']['output'];
    };
    readonly learnerProfile: {
      readonly byTopicJson: CodecTypes['sqlite/text@1']['output'];
      readonly id: CodecTypes['sqlite/text@1']['output'];
      readonly overallJson: CodecTypes['sqlite/text@1']['output'];
      readonly profileConfidence: CodecTypes['sqlite/real@1']['output'];
      readonly readinessIndex: CodecTypes['sqlite/integer@1']['output'];
      readonly studentId: CodecTypes['sqlite/text@1']['output'];
      readonly updatedAt: CodecTypes['sqlite/datetime@1']['output'];
    };
    readonly question: {
      readonly concept: CodecTypes['sqlite/text@1']['output'];
      readonly correctOption: CodecTypes['sqlite/text@1']['output'];
      readonly difficulty: CodecTypes['sqlite/text@1']['output'];
      readonly distractorsJson: CodecTypes['sqlite/text@1']['output'];
      readonly estimatedTimeSeconds: CodecTypes['sqlite/integer@1']['output'];
      readonly explanation: CodecTypes['sqlite/text@1']['output'];
      readonly id: CodecTypes['sqlite/text@1']['output'];
      readonly optionsJson: CodecTypes['sqlite/text@1']['output'];
      readonly questionText: CodecTypes['sqlite/text@1']['output'];
      readonly subject: CodecTypes['sqlite/text@1']['output'];
      readonly subtopic: CodecTypes['sqlite/text@1']['output'];
      readonly topic: CodecTypes['sqlite/text@1']['output'];
    };
    readonly student: {
      readonly createdAt: CodecTypes['sqlite/datetime@1']['output'];
      readonly id: CodecTypes['sqlite/text@1']['output'];
      readonly name: CodecTypes['sqlite/text@1']['output'] | null;
      readonly subjects: CodecTypes['sqlite/text@1']['output'];
      readonly targetExam: CodecTypes['sqlite/text@1']['output'];
      readonly targetScore: CodecTypes['sqlite/integer@1']['output'];
    };
  };
};
export type StorageColumnInputTypes = {
  readonly __unbound__: {
    readonly attempt: {
      readonly correct: CodecTypes['sqlite/integer@1']['input'];
      readonly createdAt: CodecTypes['sqlite/datetime@1']['input'];
      readonly diagnosticId: CodecTypes['sqlite/text@1']['input'];
      readonly id: CodecTypes['sqlite/text@1']['input'];
      readonly inferredConfidence: CodecTypes['sqlite/text@1']['input'];
      readonly inferredMasterySignal: CodecTypes['sqlite/text@1']['input'];
      readonly questionId: CodecTypes['sqlite/text@1']['input'];
      readonly responseTimeSeconds: CodecTypes['sqlite/integer@1']['input'];
      readonly selectedOption: CodecTypes['sqlite/text@1']['input'];
      readonly studentId: CodecTypes['sqlite/text@1']['input'];
      readonly telemetryJson: CodecTypes['sqlite/text@1']['input'];
    };
    readonly diagnosticSession: {
      readonly completedAt: CodecTypes['sqlite/datetime@1']['input'] | null;
      readonly createdAt: CodecTypes['sqlite/datetime@1']['input'];
      readonly id: CodecTypes['sqlite/text@1']['input'];
      readonly studentId: CodecTypes['sqlite/text@1']['input'];
      readonly subject: CodecTypes['sqlite/text@1']['input'];
    };
    readonly intervention: {
      readonly actionType: CodecTypes['sqlite/text@1']['input'];
      readonly completedAt: CodecTypes['sqlite/datetime@1']['input'] | null;
      readonly contentJson: CodecTypes['sqlite/text@1']['input'];
      readonly id: CodecTypes['sqlite/text@1']['input'];
      readonly improved: CodecTypes['sqlite/integer@1']['input'] | null;
      readonly masteryAfter: CodecTypes['sqlite/real@1']['input'] | null;
      readonly masteryBefore: CodecTypes['sqlite/real@1']['input'];
      readonly startedAt: CodecTypes['sqlite/datetime@1']['input'];
      readonly studentId: CodecTypes['sqlite/text@1']['input'];
      readonly topic: CodecTypes['sqlite/text@1']['input'];
    };
    readonly learnerProfile: {
      readonly byTopicJson: CodecTypes['sqlite/text@1']['input'];
      readonly id: CodecTypes['sqlite/text@1']['input'];
      readonly overallJson: CodecTypes['sqlite/text@1']['input'];
      readonly profileConfidence: CodecTypes['sqlite/real@1']['input'];
      readonly readinessIndex: CodecTypes['sqlite/integer@1']['input'];
      readonly studentId: CodecTypes['sqlite/text@1']['input'];
      readonly updatedAt: CodecTypes['sqlite/datetime@1']['input'];
    };
    readonly question: {
      readonly concept: CodecTypes['sqlite/text@1']['input'];
      readonly correctOption: CodecTypes['sqlite/text@1']['input'];
      readonly difficulty: CodecTypes['sqlite/text@1']['input'];
      readonly distractorsJson: CodecTypes['sqlite/text@1']['input'];
      readonly estimatedTimeSeconds: CodecTypes['sqlite/integer@1']['input'];
      readonly explanation: CodecTypes['sqlite/text@1']['input'];
      readonly id: CodecTypes['sqlite/text@1']['input'];
      readonly optionsJson: CodecTypes['sqlite/text@1']['input'];
      readonly questionText: CodecTypes['sqlite/text@1']['input'];
      readonly subject: CodecTypes['sqlite/text@1']['input'];
      readonly subtopic: CodecTypes['sqlite/text@1']['input'];
      readonly topic: CodecTypes['sqlite/text@1']['input'];
    };
    readonly student: {
      readonly createdAt: CodecTypes['sqlite/datetime@1']['input'];
      readonly id: CodecTypes['sqlite/text@1']['input'];
      readonly name: CodecTypes['sqlite/text@1']['input'] | null;
      readonly subjects: CodecTypes['sqlite/text@1']['input'];
      readonly targetExam: CodecTypes['sqlite/text@1']['input'];
      readonly targetScore: CodecTypes['sqlite/integer@1']['input'];
    };
  };
};

export namespace Models {
  export type Student = {
    id: CodecTypes['sqlite/text@1']['output'];
    name: CodecTypes['sqlite/text@1']['output'] | null;
    targetExam: CodecTypes['sqlite/text@1']['output'];
    targetScore: CodecTypes['sqlite/integer@1']['output'];
    subjects: CodecTypes['sqlite/text@1']['output'];
    createdAt: CodecTypes['sqlite/datetime@1']['output'];
    attempts: Attempt[];
    interventions: Intervention[];
    profile: LearnerProfile | null;
    sessions: DiagnosticSession[];
    readonly [RelationKeys]?: 'attempts' | 'interventions' | 'profile' | 'sessions';
  };
  export type DiagnosticSession = {
    id: CodecTypes['sqlite/text@1']['output'];
    studentId: CodecTypes['sqlite/text@1']['output'];
    subject: CodecTypes['sqlite/text@1']['output'];
    createdAt: CodecTypes['sqlite/datetime@1']['output'];
    completedAt: CodecTypes['sqlite/datetime@1']['output'] | null;
    student: Student;
    readonly [RelationKeys]?: 'student';
  };
  export type Question = {
    id: CodecTypes['sqlite/text@1']['output'];
    subject: CodecTypes['sqlite/text@1']['output'];
    topic: CodecTypes['sqlite/text@1']['output'];
    subtopic: CodecTypes['sqlite/text@1']['output'];
    concept: CodecTypes['sqlite/text@1']['output'];
    difficulty: CodecTypes['sqlite/text@1']['output'];
    estimatedTimeSeconds: CodecTypes['sqlite/integer@1']['output'];
    questionText: CodecTypes['sqlite/text@1']['output'];
    optionsJson: CodecTypes['sqlite/text@1']['output'];
    correctOption: CodecTypes['sqlite/text@1']['output'];
    distractorsJson: CodecTypes['sqlite/text@1']['output'];
    explanation: CodecTypes['sqlite/text@1']['output'];
    readonly [RelationKeys]?: never;
  };
  export type Attempt = {
    id: CodecTypes['sqlite/text@1']['output'];
    studentId: CodecTypes['sqlite/text@1']['output'];
    questionId: CodecTypes['sqlite/text@1']['output'];
    diagnosticId: CodecTypes['sqlite/text@1']['output'];
    selectedOption: CodecTypes['sqlite/text@1']['output'];
    correct: CodecTypes['sqlite/integer@1']['output'];
    responseTimeSeconds: CodecTypes['sqlite/integer@1']['output'];
    inferredConfidence: CodecTypes['sqlite/text@1']['output'];
    inferredMasterySignal: CodecTypes['sqlite/text@1']['output'];
    telemetryJson: CodecTypes['sqlite/text@1']['output'];
    createdAt: CodecTypes['sqlite/datetime@1']['output'];
    student: Student;
    readonly [RelationKeys]?: 'student';
  };
  export type LearnerProfile = {
    id: CodecTypes['sqlite/text@1']['output'];
    studentId: CodecTypes['sqlite/text@1']['output'];
    overallJson: CodecTypes['sqlite/text@1']['output'];
    byTopicJson: CodecTypes['sqlite/text@1']['output'];
    readinessIndex: CodecTypes['sqlite/integer@1']['output'];
    profileConfidence: CodecTypes['sqlite/real@1']['output'];
    updatedAt: CodecTypes['sqlite/datetime@1']['output'];
    student: Student;
    readonly [RelationKeys]?: 'student';
  };
  export type Intervention = {
    id: CodecTypes['sqlite/text@1']['output'];
    studentId: CodecTypes['sqlite/text@1']['output'];
    topic: CodecTypes['sqlite/text@1']['output'];
    actionType: CodecTypes['sqlite/text@1']['output'];
    contentJson: CodecTypes['sqlite/text@1']['output'];
    startedAt: CodecTypes['sqlite/datetime@1']['output'];
    completedAt: CodecTypes['sqlite/datetime@1']['output'] | null;
    masteryBefore: CodecTypes['sqlite/real@1']['output'];
    masteryAfter: CodecTypes['sqlite/real@1']['output'] | null;
    improved: CodecTypes['sqlite/integer@1']['output'] | null;
    student: Student;
    readonly [RelationKeys]?: 'student';
  };
}

export declare const models: {
  Student: Models.Student;
  DiagnosticSession: Models.DiagnosticSession;
  Question: Models.Question;
  Attempt: Models.Attempt;
  LearnerProfile: Models.LearnerProfile;
  Intervention: Models.Intervention;
};

export type TypeMaps = TypeMapsType<
  CodecTypes,
  QueryOperationTypes,
  FieldOutputTypes,
  FieldInputTypes,
  StorageColumnTypes,
  StorageColumnInputTypes,
  AggregateTypes
>;

type ContractBase = Omit<
  ContractType<{
    readonly namespaces: {
      readonly __unbound__: {
        readonly id: '__unbound__';
        readonly kind: 'sqlite-namespace';
        readonly entries: {
          readonly table: {
            readonly attempt: {
              columns: {
                readonly id: {
                  readonly nativeType: 'text';
                  readonly codecId: 'sqlite/text@1';
                  readonly nullable: false;
                };
                readonly studentId: {
                  readonly nativeType: 'text';
                  readonly codecId: 'sqlite/text@1';
                  readonly nullable: false;
                };
                readonly questionId: {
                  readonly nativeType: 'text';
                  readonly codecId: 'sqlite/text@1';
                  readonly nullable: false;
                };
                readonly diagnosticId: {
                  readonly nativeType: 'text';
                  readonly codecId: 'sqlite/text@1';
                  readonly nullable: false;
                };
                readonly selectedOption: {
                  readonly nativeType: 'text';
                  readonly codecId: 'sqlite/text@1';
                  readonly nullable: false;
                };
                readonly correct: {
                  readonly nativeType: 'integer';
                  readonly codecId: 'sqlite/integer@1';
                  readonly nullable: false;
                };
                readonly responseTimeSeconds: {
                  readonly nativeType: 'integer';
                  readonly codecId: 'sqlite/integer@1';
                  readonly nullable: false;
                };
                readonly inferredConfidence: {
                  readonly nativeType: 'text';
                  readonly codecId: 'sqlite/text@1';
                  readonly nullable: false;
                };
                readonly inferredMasterySignal: {
                  readonly nativeType: 'text';
                  readonly codecId: 'sqlite/text@1';
                  readonly nullable: false;
                };
                readonly telemetryJson: {
                  readonly nativeType: 'text';
                  readonly codecId: 'sqlite/text@1';
                  readonly nullable: false;
                };
                readonly createdAt: {
                  readonly nativeType: 'text';
                  readonly codecId: 'sqlite/datetime@1';
                  readonly nullable: false;
                  readonly default: { readonly kind: 'function'; readonly expression: 'now()' };
                };
              };
              primaryKey: { readonly columns: readonly ['id'] };
              uniques: readonly [];
              indexes: readonly [
                {
                  readonly name: 'attempt_studentId_idx_bf255322';
                  readonly prefix: 'attempt_studentId_idx';
                  readonly columns: readonly ['studentId'];
                  readonly unique: false;
                },
                {
                  readonly name: 'attempt_diagnosticId_idx_928861a5';
                  readonly prefix: 'attempt_diagnosticId_idx';
                  readonly columns: readonly ['diagnosticId'];
                  readonly unique: false;
                },
              ];
              foreignKeys: readonly [
                {
                  readonly source: {
                    readonly namespaceId: '__unbound__' & NamespaceId;
                    readonly tableName: 'attempt';
                    readonly columns: readonly ['studentId'];
                  };
                  readonly target: {
                    readonly namespaceId: '__unbound__' & NamespaceId;
                    readonly tableName: 'student';
                    readonly columns: readonly ['id'];
                  };
                },
              ];
            };
            readonly diagnosticSession: {
              columns: {
                readonly id: {
                  readonly nativeType: 'text';
                  readonly codecId: 'sqlite/text@1';
                  readonly nullable: false;
                };
                readonly studentId: {
                  readonly nativeType: 'text';
                  readonly codecId: 'sqlite/text@1';
                  readonly nullable: false;
                };
                readonly subject: {
                  readonly nativeType: 'text';
                  readonly codecId: 'sqlite/text@1';
                  readonly nullable: false;
                };
                readonly createdAt: {
                  readonly nativeType: 'text';
                  readonly codecId: 'sqlite/datetime@1';
                  readonly nullable: false;
                  readonly default: { readonly kind: 'function'; readonly expression: 'now()' };
                };
                readonly completedAt: {
                  readonly nativeType: 'text';
                  readonly codecId: 'sqlite/datetime@1';
                  readonly nullable: true;
                };
              };
              primaryKey: { readonly columns: readonly ['id'] };
              uniques: readonly [];
              indexes: readonly [
                {
                  readonly name: 'diagnosticSession_studentId_idx_bf255322';
                  readonly prefix: 'diagnosticSession_studentId_idx';
                  readonly columns: readonly ['studentId'];
                  readonly unique: false;
                },
              ];
              foreignKeys: readonly [
                {
                  readonly source: {
                    readonly namespaceId: '__unbound__' & NamespaceId;
                    readonly tableName: 'diagnosticSession';
                    readonly columns: readonly ['studentId'];
                  };
                  readonly target: {
                    readonly namespaceId: '__unbound__' & NamespaceId;
                    readonly tableName: 'student';
                    readonly columns: readonly ['id'];
                  };
                },
              ];
            };
            readonly intervention: {
              columns: {
                readonly id: {
                  readonly nativeType: 'text';
                  readonly codecId: 'sqlite/text@1';
                  readonly nullable: false;
                };
                readonly studentId: {
                  readonly nativeType: 'text';
                  readonly codecId: 'sqlite/text@1';
                  readonly nullable: false;
                };
                readonly topic: {
                  readonly nativeType: 'text';
                  readonly codecId: 'sqlite/text@1';
                  readonly nullable: false;
                };
                readonly actionType: {
                  readonly nativeType: 'text';
                  readonly codecId: 'sqlite/text@1';
                  readonly nullable: false;
                };
                readonly contentJson: {
                  readonly nativeType: 'text';
                  readonly codecId: 'sqlite/text@1';
                  readonly nullable: false;
                };
                readonly startedAt: {
                  readonly nativeType: 'text';
                  readonly codecId: 'sqlite/datetime@1';
                  readonly nullable: false;
                  readonly default: { readonly kind: 'function'; readonly expression: 'now()' };
                };
                readonly completedAt: {
                  readonly nativeType: 'text';
                  readonly codecId: 'sqlite/datetime@1';
                  readonly nullable: true;
                };
                readonly masteryBefore: {
                  readonly nativeType: 'real';
                  readonly codecId: 'sqlite/real@1';
                  readonly nullable: false;
                };
                readonly masteryAfter: {
                  readonly nativeType: 'real';
                  readonly codecId: 'sqlite/real@1';
                  readonly nullable: true;
                };
                readonly improved: {
                  readonly nativeType: 'integer';
                  readonly codecId: 'sqlite/integer@1';
                  readonly nullable: true;
                };
              };
              primaryKey: { readonly columns: readonly ['id'] };
              uniques: readonly [];
              indexes: readonly [
                {
                  readonly name: 'intervention_studentId_idx_bf255322';
                  readonly prefix: 'intervention_studentId_idx';
                  readonly columns: readonly ['studentId'];
                  readonly unique: false;
                },
              ];
              foreignKeys: readonly [
                {
                  readonly source: {
                    readonly namespaceId: '__unbound__' & NamespaceId;
                    readonly tableName: 'intervention';
                    readonly columns: readonly ['studentId'];
                  };
                  readonly target: {
                    readonly namespaceId: '__unbound__' & NamespaceId;
                    readonly tableName: 'student';
                    readonly columns: readonly ['id'];
                  };
                },
              ];
            };
            readonly learnerProfile: {
              columns: {
                readonly id: {
                  readonly nativeType: 'text';
                  readonly codecId: 'sqlite/text@1';
                  readonly nullable: false;
                };
                readonly studentId: {
                  readonly nativeType: 'text';
                  readonly codecId: 'sqlite/text@1';
                  readonly nullable: false;
                };
                readonly overallJson: {
                  readonly nativeType: 'text';
                  readonly codecId: 'sqlite/text@1';
                  readonly nullable: false;
                };
                readonly byTopicJson: {
                  readonly nativeType: 'text';
                  readonly codecId: 'sqlite/text@1';
                  readonly nullable: false;
                };
                readonly readinessIndex: {
                  readonly nativeType: 'integer';
                  readonly codecId: 'sqlite/integer@1';
                  readonly nullable: false;
                };
                readonly profileConfidence: {
                  readonly nativeType: 'real';
                  readonly codecId: 'sqlite/real@1';
                  readonly nullable: false;
                };
                readonly updatedAt: {
                  readonly nativeType: 'text';
                  readonly codecId: 'sqlite/datetime@1';
                  readonly nullable: false;
                  readonly default: { readonly kind: 'function'; readonly expression: 'now()' };
                };
              };
              primaryKey: { readonly columns: readonly ['id'] };
              uniques: readonly [{ readonly columns: readonly ['studentId'] }];
              indexes: readonly [];
              foreignKeys: readonly [
                {
                  readonly source: {
                    readonly namespaceId: '__unbound__' & NamespaceId;
                    readonly tableName: 'learnerProfile';
                    readonly columns: readonly ['studentId'];
                  };
                  readonly target: {
                    readonly namespaceId: '__unbound__' & NamespaceId;
                    readonly tableName: 'student';
                    readonly columns: readonly ['id'];
                  };
                },
              ];
            };
            readonly question: {
              columns: {
                readonly id: {
                  readonly nativeType: 'text';
                  readonly codecId: 'sqlite/text@1';
                  readonly nullable: false;
                };
                readonly subject: {
                  readonly nativeType: 'text';
                  readonly codecId: 'sqlite/text@1';
                  readonly nullable: false;
                };
                readonly topic: {
                  readonly nativeType: 'text';
                  readonly codecId: 'sqlite/text@1';
                  readonly nullable: false;
                };
                readonly subtopic: {
                  readonly nativeType: 'text';
                  readonly codecId: 'sqlite/text@1';
                  readonly nullable: false;
                };
                readonly concept: {
                  readonly nativeType: 'text';
                  readonly codecId: 'sqlite/text@1';
                  readonly nullable: false;
                };
                readonly difficulty: {
                  readonly nativeType: 'text';
                  readonly codecId: 'sqlite/text@1';
                  readonly nullable: false;
                };
                readonly estimatedTimeSeconds: {
                  readonly nativeType: 'integer';
                  readonly codecId: 'sqlite/integer@1';
                  readonly nullable: false;
                };
                readonly questionText: {
                  readonly nativeType: 'text';
                  readonly codecId: 'sqlite/text@1';
                  readonly nullable: false;
                };
                readonly optionsJson: {
                  readonly nativeType: 'text';
                  readonly codecId: 'sqlite/text@1';
                  readonly nullable: false;
                };
                readonly correctOption: {
                  readonly nativeType: 'text';
                  readonly codecId: 'sqlite/text@1';
                  readonly nullable: false;
                };
                readonly distractorsJson: {
                  readonly nativeType: 'text';
                  readonly codecId: 'sqlite/text@1';
                  readonly nullable: false;
                };
                readonly explanation: {
                  readonly nativeType: 'text';
                  readonly codecId: 'sqlite/text@1';
                  readonly nullable: false;
                };
              };
              primaryKey: { readonly columns: readonly ['id'] };
              uniques: readonly [];
              indexes: readonly [
                {
                  readonly name: 'question_topic_idx_655aa1bc';
                  readonly prefix: 'question_topic_idx';
                  readonly columns: readonly ['topic'];
                  readonly unique: false;
                },
              ];
              foreignKeys: readonly [];
            };
            readonly student: {
              columns: {
                readonly id: {
                  readonly nativeType: 'text';
                  readonly codecId: 'sqlite/text@1';
                  readonly nullable: false;
                };
                readonly name: {
                  readonly nativeType: 'text';
                  readonly codecId: 'sqlite/text@1';
                  readonly nullable: true;
                };
                readonly targetExam: {
                  readonly nativeType: 'text';
                  readonly codecId: 'sqlite/text@1';
                  readonly nullable: false;
                  readonly default: {
                    readonly kind: 'literal';
                    readonly value: DefaultLiteralValue<'sqlite/text@1', 'JAMB'>;
                  };
                };
                readonly targetScore: {
                  readonly nativeType: 'integer';
                  readonly codecId: 'sqlite/integer@1';
                  readonly nullable: false;
                };
                readonly subjects: {
                  readonly nativeType: 'text';
                  readonly codecId: 'sqlite/text@1';
                  readonly nullable: false;
                };
                readonly createdAt: {
                  readonly nativeType: 'text';
                  readonly codecId: 'sqlite/datetime@1';
                  readonly nullable: false;
                  readonly default: { readonly kind: 'function'; readonly expression: 'now()' };
                };
              };
              primaryKey: { readonly columns: readonly ['id'] };
              uniques: readonly [];
              indexes: readonly [];
              foreignKeys: readonly [];
            };
          };
        };
      };
    };
    readonly storageHash: StorageHash;
  }>,
  'roots' | 'domain'
> & {
  readonly target: 'sqlite';
  readonly targetFamily: 'sql';
  readonly roots: {
    readonly student: {
      readonly namespace: '__unbound__' & NamespaceId;
      readonly model: 'Student';
    };
    readonly diagnosticSession: {
      readonly namespace: '__unbound__' & NamespaceId;
      readonly model: 'DiagnosticSession';
    };
    readonly question: {
      readonly namespace: '__unbound__' & NamespaceId;
      readonly model: 'Question';
    };
    readonly attempt: {
      readonly namespace: '__unbound__' & NamespaceId;
      readonly model: 'Attempt';
    };
    readonly learnerProfile: {
      readonly namespace: '__unbound__' & NamespaceId;
      readonly model: 'LearnerProfile';
    };
    readonly intervention: {
      readonly namespace: '__unbound__' & NamespaceId;
      readonly model: 'Intervention';
    };
  };
  readonly domain: {
    readonly namespaces: {
      readonly __unbound__: {
        readonly models: {
          readonly Attempt: {
            readonly fields: {
              readonly id: {
                readonly nullable: false;
                readonly type: { readonly kind: 'scalar'; readonly codecId: 'sqlite/text@1' };
              };
              readonly studentId: {
                readonly nullable: false;
                readonly type: { readonly kind: 'scalar'; readonly codecId: 'sqlite/text@1' };
              };
              readonly questionId: {
                readonly nullable: false;
                readonly type: { readonly kind: 'scalar'; readonly codecId: 'sqlite/text@1' };
              };
              readonly diagnosticId: {
                readonly nullable: false;
                readonly type: { readonly kind: 'scalar'; readonly codecId: 'sqlite/text@1' };
              };
              readonly selectedOption: {
                readonly nullable: false;
                readonly type: { readonly kind: 'scalar'; readonly codecId: 'sqlite/text@1' };
              };
              readonly correct: {
                readonly nullable: false;
                readonly type: { readonly kind: 'scalar'; readonly codecId: 'sqlite/integer@1' };
              };
              readonly responseTimeSeconds: {
                readonly nullable: false;
                readonly type: { readonly kind: 'scalar'; readonly codecId: 'sqlite/integer@1' };
              };
              readonly inferredConfidence: {
                readonly nullable: false;
                readonly type: { readonly kind: 'scalar'; readonly codecId: 'sqlite/text@1' };
              };
              readonly inferredMasterySignal: {
                readonly nullable: false;
                readonly type: { readonly kind: 'scalar'; readonly codecId: 'sqlite/text@1' };
              };
              readonly telemetryJson: {
                readonly nullable: false;
                readonly type: { readonly kind: 'scalar'; readonly codecId: 'sqlite/text@1' };
              };
              readonly createdAt: {
                readonly nullable: false;
                readonly type: { readonly kind: 'scalar'; readonly codecId: 'sqlite/datetime@1' };
              };
            };
            readonly relations: {
              readonly student: {
                readonly to: {
                  readonly namespace: '__unbound__' & NamespaceId;
                  readonly model: 'Student';
                };
                readonly cardinality: 'N:1';
                readonly nullable: false;
                readonly on: {
                  readonly localFields: readonly ['studentId'];
                  readonly targetFields: readonly ['id'];
                };
              };
            };
            readonly storage: {
              readonly table: 'attempt';
              readonly namespaceId: '__unbound__';
              readonly fields: {
                readonly id: { readonly column: 'id' };
                readonly studentId: { readonly column: 'studentId' };
                readonly questionId: { readonly column: 'questionId' };
                readonly diagnosticId: { readonly column: 'diagnosticId' };
                readonly selectedOption: { readonly column: 'selectedOption' };
                readonly correct: { readonly column: 'correct' };
                readonly responseTimeSeconds: { readonly column: 'responseTimeSeconds' };
                readonly inferredConfidence: { readonly column: 'inferredConfidence' };
                readonly inferredMasterySignal: { readonly column: 'inferredMasterySignal' };
                readonly telemetryJson: { readonly column: 'telemetryJson' };
                readonly createdAt: { readonly column: 'createdAt' };
              };
            };
          };
          readonly DiagnosticSession: {
            readonly fields: {
              readonly id: {
                readonly nullable: false;
                readonly type: { readonly kind: 'scalar'; readonly codecId: 'sqlite/text@1' };
              };
              readonly studentId: {
                readonly nullable: false;
                readonly type: { readonly kind: 'scalar'; readonly codecId: 'sqlite/text@1' };
              };
              readonly subject: {
                readonly nullable: false;
                readonly type: { readonly kind: 'scalar'; readonly codecId: 'sqlite/text@1' };
              };
              readonly createdAt: {
                readonly nullable: false;
                readonly type: { readonly kind: 'scalar'; readonly codecId: 'sqlite/datetime@1' };
              };
              readonly completedAt: {
                readonly nullable: true;
                readonly type: { readonly kind: 'scalar'; readonly codecId: 'sqlite/datetime@1' };
              };
            };
            readonly relations: {
              readonly student: {
                readonly to: {
                  readonly namespace: '__unbound__' & NamespaceId;
                  readonly model: 'Student';
                };
                readonly cardinality: 'N:1';
                readonly nullable: false;
                readonly on: {
                  readonly localFields: readonly ['studentId'];
                  readonly targetFields: readonly ['id'];
                };
              };
            };
            readonly storage: {
              readonly table: 'diagnosticSession';
              readonly namespaceId: '__unbound__';
              readonly fields: {
                readonly id: { readonly column: 'id' };
                readonly studentId: { readonly column: 'studentId' };
                readonly subject: { readonly column: 'subject' };
                readonly createdAt: { readonly column: 'createdAt' };
                readonly completedAt: { readonly column: 'completedAt' };
              };
            };
          };
          readonly Intervention: {
            readonly fields: {
              readonly id: {
                readonly nullable: false;
                readonly type: { readonly kind: 'scalar'; readonly codecId: 'sqlite/text@1' };
              };
              readonly studentId: {
                readonly nullable: false;
                readonly type: { readonly kind: 'scalar'; readonly codecId: 'sqlite/text@1' };
              };
              readonly topic: {
                readonly nullable: false;
                readonly type: { readonly kind: 'scalar'; readonly codecId: 'sqlite/text@1' };
              };
              readonly actionType: {
                readonly nullable: false;
                readonly type: { readonly kind: 'scalar'; readonly codecId: 'sqlite/text@1' };
              };
              readonly contentJson: {
                readonly nullable: false;
                readonly type: { readonly kind: 'scalar'; readonly codecId: 'sqlite/text@1' };
              };
              readonly startedAt: {
                readonly nullable: false;
                readonly type: { readonly kind: 'scalar'; readonly codecId: 'sqlite/datetime@1' };
              };
              readonly completedAt: {
                readonly nullable: true;
                readonly type: { readonly kind: 'scalar'; readonly codecId: 'sqlite/datetime@1' };
              };
              readonly masteryBefore: {
                readonly nullable: false;
                readonly type: { readonly kind: 'scalar'; readonly codecId: 'sqlite/real@1' };
              };
              readonly masteryAfter: {
                readonly nullable: true;
                readonly type: { readonly kind: 'scalar'; readonly codecId: 'sqlite/real@1' };
              };
              readonly improved: {
                readonly nullable: true;
                readonly type: { readonly kind: 'scalar'; readonly codecId: 'sqlite/integer@1' };
              };
            };
            readonly relations: {
              readonly student: {
                readonly to: {
                  readonly namespace: '__unbound__' & NamespaceId;
                  readonly model: 'Student';
                };
                readonly cardinality: 'N:1';
                readonly nullable: false;
                readonly on: {
                  readonly localFields: readonly ['studentId'];
                  readonly targetFields: readonly ['id'];
                };
              };
            };
            readonly storage: {
              readonly table: 'intervention';
              readonly namespaceId: '__unbound__';
              readonly fields: {
                readonly id: { readonly column: 'id' };
                readonly studentId: { readonly column: 'studentId' };
                readonly topic: { readonly column: 'topic' };
                readonly actionType: { readonly column: 'actionType' };
                readonly contentJson: { readonly column: 'contentJson' };
                readonly startedAt: { readonly column: 'startedAt' };
                readonly completedAt: { readonly column: 'completedAt' };
                readonly masteryBefore: { readonly column: 'masteryBefore' };
                readonly masteryAfter: { readonly column: 'masteryAfter' };
                readonly improved: { readonly column: 'improved' };
              };
            };
          };
          readonly LearnerProfile: {
            readonly fields: {
              readonly id: {
                readonly nullable: false;
                readonly type: { readonly kind: 'scalar'; readonly codecId: 'sqlite/text@1' };
              };
              readonly studentId: {
                readonly nullable: false;
                readonly type: { readonly kind: 'scalar'; readonly codecId: 'sqlite/text@1' };
              };
              readonly overallJson: {
                readonly nullable: false;
                readonly type: { readonly kind: 'scalar'; readonly codecId: 'sqlite/text@1' };
              };
              readonly byTopicJson: {
                readonly nullable: false;
                readonly type: { readonly kind: 'scalar'; readonly codecId: 'sqlite/text@1' };
              };
              readonly readinessIndex: {
                readonly nullable: false;
                readonly type: { readonly kind: 'scalar'; readonly codecId: 'sqlite/integer@1' };
              };
              readonly profileConfidence: {
                readonly nullable: false;
                readonly type: { readonly kind: 'scalar'; readonly codecId: 'sqlite/real@1' };
              };
              readonly updatedAt: {
                readonly nullable: false;
                readonly type: { readonly kind: 'scalar'; readonly codecId: 'sqlite/datetime@1' };
              };
            };
            readonly relations: {
              readonly student: {
                readonly to: {
                  readonly namespace: '__unbound__' & NamespaceId;
                  readonly model: 'Student';
                };
                readonly cardinality: 'N:1';
                readonly nullable: false;
                readonly on: {
                  readonly localFields: readonly ['studentId'];
                  readonly targetFields: readonly ['id'];
                };
              };
            };
            readonly storage: {
              readonly table: 'learnerProfile';
              readonly namespaceId: '__unbound__';
              readonly fields: {
                readonly id: { readonly column: 'id' };
                readonly studentId: { readonly column: 'studentId' };
                readonly overallJson: { readonly column: 'overallJson' };
                readonly byTopicJson: { readonly column: 'byTopicJson' };
                readonly readinessIndex: { readonly column: 'readinessIndex' };
                readonly profileConfidence: { readonly column: 'profileConfidence' };
                readonly updatedAt: { readonly column: 'updatedAt' };
              };
            };
          };
          readonly Question: {
            readonly fields: {
              readonly id: {
                readonly nullable: false;
                readonly type: { readonly kind: 'scalar'; readonly codecId: 'sqlite/text@1' };
              };
              readonly subject: {
                readonly nullable: false;
                readonly type: { readonly kind: 'scalar'; readonly codecId: 'sqlite/text@1' };
              };
              readonly topic: {
                readonly nullable: false;
                readonly type: { readonly kind: 'scalar'; readonly codecId: 'sqlite/text@1' };
              };
              readonly subtopic: {
                readonly nullable: false;
                readonly type: { readonly kind: 'scalar'; readonly codecId: 'sqlite/text@1' };
              };
              readonly concept: {
                readonly nullable: false;
                readonly type: { readonly kind: 'scalar'; readonly codecId: 'sqlite/text@1' };
              };
              readonly difficulty: {
                readonly nullable: false;
                readonly type: { readonly kind: 'scalar'; readonly codecId: 'sqlite/text@1' };
              };
              readonly estimatedTimeSeconds: {
                readonly nullable: false;
                readonly type: { readonly kind: 'scalar'; readonly codecId: 'sqlite/integer@1' };
              };
              readonly questionText: {
                readonly nullable: false;
                readonly type: { readonly kind: 'scalar'; readonly codecId: 'sqlite/text@1' };
              };
              readonly optionsJson: {
                readonly nullable: false;
                readonly type: { readonly kind: 'scalar'; readonly codecId: 'sqlite/text@1' };
              };
              readonly correctOption: {
                readonly nullable: false;
                readonly type: { readonly kind: 'scalar'; readonly codecId: 'sqlite/text@1' };
              };
              readonly distractorsJson: {
                readonly nullable: false;
                readonly type: { readonly kind: 'scalar'; readonly codecId: 'sqlite/text@1' };
              };
              readonly explanation: {
                readonly nullable: false;
                readonly type: { readonly kind: 'scalar'; readonly codecId: 'sqlite/text@1' };
              };
            };
            readonly relations: Record<string, never>;
            readonly storage: {
              readonly table: 'question';
              readonly namespaceId: '__unbound__';
              readonly fields: {
                readonly id: { readonly column: 'id' };
                readonly subject: { readonly column: 'subject' };
                readonly topic: { readonly column: 'topic' };
                readonly subtopic: { readonly column: 'subtopic' };
                readonly concept: { readonly column: 'concept' };
                readonly difficulty: { readonly column: 'difficulty' };
                readonly estimatedTimeSeconds: { readonly column: 'estimatedTimeSeconds' };
                readonly questionText: { readonly column: 'questionText' };
                readonly optionsJson: { readonly column: 'optionsJson' };
                readonly correctOption: { readonly column: 'correctOption' };
                readonly distractorsJson: { readonly column: 'distractorsJson' };
                readonly explanation: { readonly column: 'explanation' };
              };
            };
          };
          readonly Student: {
            readonly fields: {
              readonly id: {
                readonly nullable: false;
                readonly type: { readonly kind: 'scalar'; readonly codecId: 'sqlite/text@1' };
              };
              readonly name: {
                readonly nullable: true;
                readonly type: { readonly kind: 'scalar'; readonly codecId: 'sqlite/text@1' };
              };
              readonly targetExam: {
                readonly nullable: false;
                readonly type: { readonly kind: 'scalar'; readonly codecId: 'sqlite/text@1' };
              };
              readonly targetScore: {
                readonly nullable: false;
                readonly type: { readonly kind: 'scalar'; readonly codecId: 'sqlite/integer@1' };
              };
              readonly subjects: {
                readonly nullable: false;
                readonly type: { readonly kind: 'scalar'; readonly codecId: 'sqlite/text@1' };
              };
              readonly createdAt: {
                readonly nullable: false;
                readonly type: { readonly kind: 'scalar'; readonly codecId: 'sqlite/datetime@1' };
              };
            };
            readonly relations: {
              readonly attempts: {
                readonly to: {
                  readonly namespace: '__unbound__' & NamespaceId;
                  readonly model: 'Attempt';
                };
                readonly cardinality: '1:N';
                readonly on: {
                  readonly localFields: readonly ['id'];
                  readonly targetFields: readonly ['studentId'];
                };
              };
              readonly interventions: {
                readonly to: {
                  readonly namespace: '__unbound__' & NamespaceId;
                  readonly model: 'Intervention';
                };
                readonly cardinality: '1:N';
                readonly on: {
                  readonly localFields: readonly ['id'];
                  readonly targetFields: readonly ['studentId'];
                };
              };
              readonly profile: {
                readonly to: {
                  readonly namespace: '__unbound__' & NamespaceId;
                  readonly model: 'LearnerProfile';
                };
                readonly cardinality: '1:1';
                readonly nullable: true;
                readonly on: {
                  readonly localFields: readonly ['id'];
                  readonly targetFields: readonly ['studentId'];
                };
              };
              readonly sessions: {
                readonly to: {
                  readonly namespace: '__unbound__' & NamespaceId;
                  readonly model: 'DiagnosticSession';
                };
                readonly cardinality: '1:N';
                readonly on: {
                  readonly localFields: readonly ['id'];
                  readonly targetFields: readonly ['studentId'];
                };
              };
            };
            readonly storage: {
              readonly table: 'student';
              readonly namespaceId: '__unbound__';
              readonly fields: {
                readonly id: { readonly column: 'id' };
                readonly name: { readonly column: 'name' };
                readonly targetExam: { readonly column: 'targetExam' };
                readonly targetScore: { readonly column: 'targetScore' };
                readonly subjects: { readonly column: 'subjects' };
                readonly createdAt: { readonly column: 'createdAt' };
              };
            };
          };
        };
      };
    };
  };
  readonly capabilities: {
    readonly sql: {
      readonly enums: false;
      readonly foreignKeys: true;
      readonly jsonAgg: true;
      readonly lateral: false;
      readonly limit: true;
      readonly orderBy: true;
      readonly returning: true;
    };
  };
  readonly extensions: {};
  readonly meta: {};

  readonly profileHash: ProfileHash;
};

export type Contract = ContractWithTypeMaps<ContractBase, TypeMaps>;

export type Namespaces = Contract['storage']['namespaces'];
