// ⚠️  GENERATED FILE - DO NOT EDIT
// This file is automatically generated by 'prisma contract emit'.
// To regenerate, run: prisma contract emit
import type { QueryOperationTypes as PgAdapterQueryOps } from '@prisma/orm-postgres/adapter/operation-types';
import type {
  Bit,
  Char,
  CodecTypes as PgTypes,
  Interval,
  JsonValue,
  Numeric,
  Time,
  TimeString,
  Timestamp,
  TimestampString,
  Timestamptz,
  TimestamptzString,
  Timetz,
  VarBit,
  Varchar,
} from '@prisma/orm-postgres/target/codec-types';

import type {
  ContractWithTypeMaps,
  RelationKeys,
  TypeMaps as TypeMapsType,
} from '@prisma/orm-postgres/family-contract/types';
import type {
  Contract as ContractType,
  ExecutionHashBase,
  NamespaceId,
  ProfileHashBase,
  StorageHashBase,
} from '@prisma/orm-postgres/contract/types';

export type StorageHash =
  StorageHashBase<'c90dc762684d433b587cad8baead46ba89f05924a2a6e566a38db4fe33824000'>;
export type ExecutionHash = ExecutionHashBase<string>;
export type ProfileHash =
  ProfileHashBase<'3916f444a8a17ad749191acf9e08dad97d1a327b88c2f1d45d12f240296aa8b2'>;

export type CodecTypes = PgTypes;
export type LaneCodecTypes = CodecTypes;
export type QueryOperationTypes = PgAdapterQueryOps<CodecTypes>;
export type AggregateTypes = {
  readonly avg: {
    readonly byCodec: {
      readonly 'pg/float@1': { readonly output: 'pg/float8@1'; readonly nullable: true };
      readonly 'pg/float4@1': { readonly output: 'pg/float8@1'; readonly nullable: true };
      readonly 'pg/float8@1': { readonly output: 'pg/float8@1'; readonly nullable: true };
      readonly 'pg/int@1': { readonly output: 'pg/float8@1'; readonly nullable: true };
      readonly 'pg/int2@1': { readonly output: 'pg/float8@1'; readonly nullable: true };
      readonly 'pg/int4@1': { readonly output: 'pg/float8@1'; readonly nullable: true };
      readonly 'pg/int8@1': { readonly output: 'pg/float8@1'; readonly nullable: true };
      readonly 'pg/int8number@1': { readonly output: 'pg/float8@1'; readonly nullable: true };
      readonly 'pg/interval@1': { readonly output: 'pg/interval@1'; readonly nullable: true };
      readonly 'pg/numeric@1': { readonly output: 'pg/numeric@1'; readonly nullable: true };
      readonly 'pg/time-string@1': { readonly output: 'pg/interval@1'; readonly nullable: true };
      readonly 'pg/time-temporal@1': { readonly output: 'pg/interval@1'; readonly nullable: true };
      readonly 'pg/unboundedint@1': { readonly output: 'pg/float8@1'; readonly nullable: true };
      readonly 'sql/float@1': { readonly output: 'pg/float8@1'; readonly nullable: true };
      readonly 'sql/int@1': { readonly output: 'pg/float8@1'; readonly nullable: true };
    };
  };
  readonly avgDecimal: {
    readonly byCodec: {
      readonly 'pg/int@1': { readonly output: 'pg/numeric@1'; readonly nullable: true };
      readonly 'pg/int2@1': { readonly output: 'pg/numeric@1'; readonly nullable: true };
      readonly 'pg/int4@1': { readonly output: 'pg/numeric@1'; readonly nullable: true };
      readonly 'pg/int8@1': { readonly output: 'pg/numeric@1'; readonly nullable: true };
      readonly 'pg/int8number@1': { readonly output: 'pg/numeric@1'; readonly nullable: true };
      readonly 'pg/numeric@1': { readonly output: 'pg/numeric@1'; readonly nullable: true };
      readonly 'pg/unboundedint@1': { readonly output: 'pg/numeric@1'; readonly nullable: true };
      readonly 'sql/int@1': { readonly output: 'pg/numeric@1'; readonly nullable: true };
    };
  };
  readonly count: {
    readonly byCodec: {};
    readonly withoutInput: { readonly output: 'pg/int8number@1'; readonly nullable: false };
    readonly anyInput: { readonly output: 'pg/int8number@1'; readonly nullable: false };
  };
  readonly countBigInt: {
    readonly byCodec: {};
    readonly withoutInput: { readonly output: 'pg/int8@1'; readonly nullable: false };
    readonly anyInput: { readonly output: 'pg/int8@1'; readonly nullable: false };
  };
  readonly max: {
    readonly byCodec: {
      readonly 'pg/char@1': { readonly output: 'pg/char@1'; readonly nullable: true };
      readonly 'pg/date-string@1': { readonly output: 'pg/date-string@1'; readonly nullable: true };
      readonly 'pg/date-temporal@1': {
        readonly output: 'pg/date-temporal@1';
        readonly nullable: true;
      };
      readonly 'pg/enum@1': { readonly output: 'pg/enum@1'; readonly nullable: true };
      readonly 'pg/float@1': { readonly output: 'pg/float@1'; readonly nullable: true };
      readonly 'pg/float4@1': { readonly output: 'pg/float4@1'; readonly nullable: true };
      readonly 'pg/float8@1': { readonly output: 'pg/float8@1'; readonly nullable: true };
      readonly 'pg/inet@1': { readonly output: 'pg/inet@1'; readonly nullable: true };
      readonly 'pg/int@1': { readonly output: 'pg/int@1'; readonly nullable: true };
      readonly 'pg/int2@1': { readonly output: 'pg/int2@1'; readonly nullable: true };
      readonly 'pg/int4@1': { readonly output: 'pg/int4@1'; readonly nullable: true };
      readonly 'pg/int8@1': { readonly output: 'pg/int8@1'; readonly nullable: true };
      readonly 'pg/int8number@1': { readonly output: 'pg/int8number@1'; readonly nullable: true };
      readonly 'pg/interval@1': { readonly output: 'pg/interval@1'; readonly nullable: true };
      readonly 'pg/numeric@1': { readonly output: 'pg/numeric@1'; readonly nullable: true };
      readonly 'pg/text-array@1': { readonly output: 'pg/text-array@1'; readonly nullable: true };
      readonly 'pg/text@1': { readonly output: 'pg/text@1'; readonly nullable: true };
      readonly 'pg/time-string@1': { readonly output: 'pg/time-string@1'; readonly nullable: true };
      readonly 'pg/time-temporal@1': {
        readonly output: 'pg/time-temporal@1';
        readonly nullable: true;
      };
      readonly 'pg/timestamp-string@1': {
        readonly output: 'pg/timestamp-string@1';
        readonly nullable: true;
      };
      readonly 'pg/timestamp-temporal@1': {
        readonly output: 'pg/timestamp-temporal@1';
        readonly nullable: true;
      };
      readonly 'pg/timestamptz-string@1': {
        readonly output: 'pg/timestamptz-string@1';
        readonly nullable: true;
      };
      readonly 'pg/timestamptz-temporal@1': {
        readonly output: 'pg/timestamptz-temporal@1';
        readonly nullable: true;
      };
      readonly 'pg/timetz@1': { readonly output: 'pg/timetz@1'; readonly nullable: true };
      readonly 'pg/unboundedint@1': {
        readonly output: 'pg/unboundedint@1';
        readonly nullable: true;
      };
      readonly 'pg/varchar@1': { readonly output: 'pg/text@1'; readonly nullable: true };
      readonly 'sql/char@1': { readonly output: 'sql/char@1'; readonly nullable: true };
      readonly 'sql/float@1': { readonly output: 'sql/float@1'; readonly nullable: true };
      readonly 'sql/int@1': { readonly output: 'sql/int@1'; readonly nullable: true };
      readonly 'sql/text@1': { readonly output: 'sql/text@1'; readonly nullable: true };
      readonly 'sql/varchar@1': { readonly output: 'pg/text@1'; readonly nullable: true };
    };
  };
  readonly min: {
    readonly byCodec: {
      readonly 'pg/char@1': { readonly output: 'pg/char@1'; readonly nullable: true };
      readonly 'pg/date-string@1': { readonly output: 'pg/date-string@1'; readonly nullable: true };
      readonly 'pg/date-temporal@1': {
        readonly output: 'pg/date-temporal@1';
        readonly nullable: true;
      };
      readonly 'pg/enum@1': { readonly output: 'pg/enum@1'; readonly nullable: true };
      readonly 'pg/float@1': { readonly output: 'pg/float@1'; readonly nullable: true };
      readonly 'pg/float4@1': { readonly output: 'pg/float4@1'; readonly nullable: true };
      readonly 'pg/float8@1': { readonly output: 'pg/float8@1'; readonly nullable: true };
      readonly 'pg/inet@1': { readonly output: 'pg/inet@1'; readonly nullable: true };
      readonly 'pg/int@1': { readonly output: 'pg/int@1'; readonly nullable: true };
      readonly 'pg/int2@1': { readonly output: 'pg/int2@1'; readonly nullable: true };
      readonly 'pg/int4@1': { readonly output: 'pg/int4@1'; readonly nullable: true };
      readonly 'pg/int8@1': { readonly output: 'pg/int8@1'; readonly nullable: true };
      readonly 'pg/int8number@1': { readonly output: 'pg/int8number@1'; readonly nullable: true };
      readonly 'pg/interval@1': { readonly output: 'pg/interval@1'; readonly nullable: true };
      readonly 'pg/numeric@1': { readonly output: 'pg/numeric@1'; readonly nullable: true };
      readonly 'pg/text-array@1': { readonly output: 'pg/text-array@1'; readonly nullable: true };
      readonly 'pg/text@1': { readonly output: 'pg/text@1'; readonly nullable: true };
      readonly 'pg/time-string@1': { readonly output: 'pg/time-string@1'; readonly nullable: true };
      readonly 'pg/time-temporal@1': {
        readonly output: 'pg/time-temporal@1';
        readonly nullable: true;
      };
      readonly 'pg/timestamp-string@1': {
        readonly output: 'pg/timestamp-string@1';
        readonly nullable: true;
      };
      readonly 'pg/timestamp-temporal@1': {
        readonly output: 'pg/timestamp-temporal@1';
        readonly nullable: true;
      };
      readonly 'pg/timestamptz-string@1': {
        readonly output: 'pg/timestamptz-string@1';
        readonly nullable: true;
      };
      readonly 'pg/timestamptz-temporal@1': {
        readonly output: 'pg/timestamptz-temporal@1';
        readonly nullable: true;
      };
      readonly 'pg/timetz@1': { readonly output: 'pg/timetz@1'; readonly nullable: true };
      readonly 'pg/unboundedint@1': {
        readonly output: 'pg/unboundedint@1';
        readonly nullable: true;
      };
      readonly 'pg/varchar@1': { readonly output: 'pg/text@1'; readonly nullable: true };
      readonly 'sql/char@1': { readonly output: 'sql/char@1'; readonly nullable: true };
      readonly 'sql/float@1': { readonly output: 'sql/float@1'; readonly nullable: true };
      readonly 'sql/int@1': { readonly output: 'sql/int@1'; readonly nullable: true };
      readonly 'sql/text@1': { readonly output: 'sql/text@1'; readonly nullable: true };
      readonly 'sql/varchar@1': { readonly output: 'pg/text@1'; readonly nullable: true };
    };
  };
  readonly sum: {
    readonly byCodec: {
      readonly 'pg/float@1': { readonly output: 'pg/float8@1'; readonly nullable: true };
      readonly 'pg/float4@1': { readonly output: 'pg/float4@1'; readonly nullable: true };
      readonly 'pg/float8@1': { readonly output: 'pg/float8@1'; readonly nullable: true };
      readonly 'pg/int@1': { readonly output: 'pg/int8number@1'; readonly nullable: true };
      readonly 'pg/int2@1': { readonly output: 'pg/int8number@1'; readonly nullable: true };
      readonly 'pg/int4@1': { readonly output: 'pg/int8number@1'; readonly nullable: true };
      readonly 'pg/int8@1': { readonly output: 'pg/int8number@1'; readonly nullable: true };
      readonly 'pg/int8number@1': { readonly output: 'pg/int8number@1'; readonly nullable: true };
      readonly 'pg/interval@1': { readonly output: 'pg/interval@1'; readonly nullable: true };
      readonly 'pg/numeric@1': { readonly output: 'pg/numeric@1'; readonly nullable: true };
      readonly 'pg/time-string@1': { readonly output: 'pg/interval@1'; readonly nullable: true };
      readonly 'pg/time-temporal@1': { readonly output: 'pg/interval@1'; readonly nullable: true };
      readonly 'pg/unboundedint@1': {
        readonly output: 'pg/unboundedint@1';
        readonly nullable: true;
      };
      readonly 'sql/float@1': { readonly output: 'pg/float8@1'; readonly nullable: true };
      readonly 'sql/int@1': { readonly output: 'pg/int8number@1'; readonly nullable: true };
    };
  };
  readonly sumBigInt: {
    readonly byCodec: {
      readonly 'pg/int@1': { readonly output: 'pg/int8@1'; readonly nullable: true };
      readonly 'pg/int2@1': { readonly output: 'pg/int8@1'; readonly nullable: true };
      readonly 'pg/int4@1': { readonly output: 'pg/int8@1'; readonly nullable: true };
      readonly 'pg/int8@1': { readonly output: 'pg/unboundedint@1'; readonly nullable: true };
      readonly 'pg/int8number@1': { readonly output: 'pg/unboundedint@1'; readonly nullable: true };
      readonly 'pg/unboundedint@1': {
        readonly output: 'pg/unboundedint@1';
        readonly nullable: true;
      };
      readonly 'sql/int@1': { readonly output: 'pg/int8@1'; readonly nullable: true };
    };
  };
};
type DefaultLiteralValue<CodecId extends string, Encoded> = CodecId extends keyof CodecTypes
  ? Encoded extends CodecTypes[CodecId]['json']
    ? Encoded
    : CodecTypes[CodecId]['json']
  : Encoded;

export type FieldOutputTypes = {
  readonly public: {
    readonly Attempt: {
      readonly id: CodecTypes['pg/text@1']['output'];
      readonly studentId: CodecTypes['pg/text@1']['output'];
      readonly diagnosticId: CodecTypes['pg/text@1']['output'];
      readonly interventionId: CodecTypes['pg/text@1']['output'] | null;
      readonly questionId: CodecTypes['pg/text@1']['output'];
      readonly purpose: CodecTypes['pg/text@1']['output'];
      readonly selectedOption: CodecTypes['pg/text@1']['output'] | null;
      readonly correct: CodecTypes['pg/int4@1']['output'];
      readonly responseTimeSeconds: CodecTypes['pg/int4@1']['output'];
      readonly inferredConfidence: CodecTypes['pg/text@1']['output'];
      readonly inferredMasterySignal: CodecTypes['pg/text@1']['output'];
      readonly telemetryJson: CodecTypes['pg/text@1']['output'];
      readonly diagnosisJson: CodecTypes['pg/text@1']['output'] | null;
      readonly createdAt: CodecTypes['pg/text@1']['output'];
    };
    readonly DiagnosticSession: {
      readonly id: CodecTypes['pg/text@1']['output'];
      readonly studentId: CodecTypes['pg/text@1']['output'];
      readonly subject: CodecTypes['pg/text@1']['output'];
      readonly startedAt: CodecTypes['pg/text@1']['output'];
      readonly completedAt: CodecTypes['pg/text@1']['output'] | null;
      readonly completedInSeconds: CodecTypes['pg/int4@1']['output'] | null;
    };
    readonly Intervention: {
      readonly id: CodecTypes['pg/text@1']['output'];
      readonly studentId: CodecTypes['pg/text@1']['output'];
      readonly topic: CodecTypes['pg/text@1']['output'];
      readonly actionType: CodecTypes['pg/text@1']['output'];
      readonly contentJson: CodecTypes['pg/text@1']['output'];
      readonly startedAt: CodecTypes['pg/text@1']['output'];
      readonly completedAt: CodecTypes['pg/text@1']['output'] | null;
      readonly masteryBefore: CodecTypes['pg/float8@1']['output'];
      readonly masteryAfter: CodecTypes['pg/float8@1']['output'] | null;
      readonly improved: CodecTypes['pg/int4@1']['output'] | null;
    };
    readonly LearnerProfile: {
      readonly id: CodecTypes['pg/text@1']['output'];
      readonly studentId: CodecTypes['pg/text@1']['output'];
      readonly overallJson: CodecTypes['pg/text@1']['output'];
      readonly byTopicJson: CodecTypes['pg/text@1']['output'];
      readonly headlineDiagnosisJson: CodecTypes['pg/text@1']['output'] | null;
      readonly readinessIndex: CodecTypes['pg/int4@1']['output'];
      readonly profileConfidence: CodecTypes['pg/float8@1']['output'];
      readonly updatedAt: CodecTypes['pg/text@1']['output'];
    };
    readonly Student: {
      readonly id: CodecTypes['pg/text@1']['output'];
      readonly name: CodecTypes['pg/text@1']['output'] | null;
      readonly targetExam: CodecTypes['pg/text@1']['output'];
      readonly targetScore: CodecTypes['pg/int4@1']['output'];
      readonly subjects: CodecTypes['pg/text@1']['output'];
      readonly createdAt: CodecTypes['pg/text@1']['output'];
    };
  };
};
export type FieldInputTypes = {
  readonly public: {
    readonly Attempt: {
      readonly id: CodecTypes['pg/text@1']['input'];
      readonly studentId: CodecTypes['pg/text@1']['input'];
      readonly diagnosticId: CodecTypes['pg/text@1']['input'];
      readonly interventionId: CodecTypes['pg/text@1']['input'] | null;
      readonly questionId: CodecTypes['pg/text@1']['input'];
      readonly purpose: CodecTypes['pg/text@1']['input'];
      readonly selectedOption: CodecTypes['pg/text@1']['input'] | null;
      readonly correct: CodecTypes['pg/int4@1']['input'];
      readonly responseTimeSeconds: CodecTypes['pg/int4@1']['input'];
      readonly inferredConfidence: CodecTypes['pg/text@1']['input'];
      readonly inferredMasterySignal: CodecTypes['pg/text@1']['input'];
      readonly telemetryJson: CodecTypes['pg/text@1']['input'];
      readonly diagnosisJson: CodecTypes['pg/text@1']['input'] | null;
      readonly createdAt: CodecTypes['pg/text@1']['input'];
    };
    readonly DiagnosticSession: {
      readonly id: CodecTypes['pg/text@1']['input'];
      readonly studentId: CodecTypes['pg/text@1']['input'];
      readonly subject: CodecTypes['pg/text@1']['input'];
      readonly startedAt: CodecTypes['pg/text@1']['input'];
      readonly completedAt: CodecTypes['pg/text@1']['input'] | null;
      readonly completedInSeconds: CodecTypes['pg/int4@1']['input'] | null;
    };
    readonly Intervention: {
      readonly id: CodecTypes['pg/text@1']['input'];
      readonly studentId: CodecTypes['pg/text@1']['input'];
      readonly topic: CodecTypes['pg/text@1']['input'];
      readonly actionType: CodecTypes['pg/text@1']['input'];
      readonly contentJson: CodecTypes['pg/text@1']['input'];
      readonly startedAt: CodecTypes['pg/text@1']['input'];
      readonly completedAt: CodecTypes['pg/text@1']['input'] | null;
      readonly masteryBefore: CodecTypes['pg/float8@1']['input'];
      readonly masteryAfter: CodecTypes['pg/float8@1']['input'] | null;
      readonly improved: CodecTypes['pg/int4@1']['input'] | null;
    };
    readonly LearnerProfile: {
      readonly id: CodecTypes['pg/text@1']['input'];
      readonly studentId: CodecTypes['pg/text@1']['input'];
      readonly overallJson: CodecTypes['pg/text@1']['input'];
      readonly byTopicJson: CodecTypes['pg/text@1']['input'];
      readonly headlineDiagnosisJson: CodecTypes['pg/text@1']['input'] | null;
      readonly readinessIndex: CodecTypes['pg/int4@1']['input'];
      readonly profileConfidence: CodecTypes['pg/float8@1']['input'];
      readonly updatedAt: CodecTypes['pg/text@1']['input'];
    };
    readonly Student: {
      readonly id: CodecTypes['pg/text@1']['input'];
      readonly name: CodecTypes['pg/text@1']['input'] | null;
      readonly targetExam: CodecTypes['pg/text@1']['input'];
      readonly targetScore: CodecTypes['pg/int4@1']['input'];
      readonly subjects: CodecTypes['pg/text@1']['input'];
      readonly createdAt: CodecTypes['pg/text@1']['input'];
    };
  };
};
export type StorageColumnTypes = {
  readonly public: {
    readonly attempt: {
      readonly correct: CodecTypes['pg/int4@1']['output'];
      readonly createdAt: CodecTypes['pg/text@1']['output'];
      readonly diagnosisJson: CodecTypes['pg/text@1']['output'] | null;
      readonly diagnosticId: CodecTypes['pg/text@1']['output'];
      readonly id: CodecTypes['pg/text@1']['output'];
      readonly inferredConfidence: CodecTypes['pg/text@1']['output'];
      readonly inferredMasterySignal: CodecTypes['pg/text@1']['output'];
      readonly interventionId: CodecTypes['pg/text@1']['output'] | null;
      readonly purpose: CodecTypes['pg/text@1']['output'];
      readonly questionId: CodecTypes['pg/text@1']['output'];
      readonly responseTimeSeconds: CodecTypes['pg/int4@1']['output'];
      readonly selectedOption: CodecTypes['pg/text@1']['output'] | null;
      readonly studentId: CodecTypes['pg/text@1']['output'];
      readonly telemetryJson: CodecTypes['pg/text@1']['output'];
    };
    readonly diagnosticSession: {
      readonly completedAt: CodecTypes['pg/text@1']['output'] | null;
      readonly completedInSeconds: CodecTypes['pg/int4@1']['output'] | null;
      readonly id: CodecTypes['pg/text@1']['output'];
      readonly startedAt: CodecTypes['pg/text@1']['output'];
      readonly studentId: CodecTypes['pg/text@1']['output'];
      readonly subject: CodecTypes['pg/text@1']['output'];
    };
    readonly intervention: {
      readonly actionType: CodecTypes['pg/text@1']['output'];
      readonly completedAt: CodecTypes['pg/text@1']['output'] | null;
      readonly contentJson: CodecTypes['pg/text@1']['output'];
      readonly id: CodecTypes['pg/text@1']['output'];
      readonly improved: CodecTypes['pg/int4@1']['output'] | null;
      readonly masteryAfter: CodecTypes['pg/float8@1']['output'] | null;
      readonly masteryBefore: CodecTypes['pg/float8@1']['output'];
      readonly startedAt: CodecTypes['pg/text@1']['output'];
      readonly studentId: CodecTypes['pg/text@1']['output'];
      readonly topic: CodecTypes['pg/text@1']['output'];
    };
    readonly learnerProfile: {
      readonly byTopicJson: CodecTypes['pg/text@1']['output'];
      readonly headlineDiagnosisJson: CodecTypes['pg/text@1']['output'] | null;
      readonly id: CodecTypes['pg/text@1']['output'];
      readonly overallJson: CodecTypes['pg/text@1']['output'];
      readonly profileConfidence: CodecTypes['pg/float8@1']['output'];
      readonly readinessIndex: CodecTypes['pg/int4@1']['output'];
      readonly studentId: CodecTypes['pg/text@1']['output'];
      readonly updatedAt: CodecTypes['pg/text@1']['output'];
    };
    readonly student: {
      readonly createdAt: CodecTypes['pg/text@1']['output'];
      readonly id: CodecTypes['pg/text@1']['output'];
      readonly name: CodecTypes['pg/text@1']['output'] | null;
      readonly subjects: CodecTypes['pg/text@1']['output'];
      readonly targetExam: CodecTypes['pg/text@1']['output'];
      readonly targetScore: CodecTypes['pg/int4@1']['output'];
    };
  };
};
export type StorageColumnInputTypes = {
  readonly public: {
    readonly attempt: {
      readonly correct: CodecTypes['pg/int4@1']['input'];
      readonly createdAt: CodecTypes['pg/text@1']['input'];
      readonly diagnosisJson: CodecTypes['pg/text@1']['input'] | null;
      readonly diagnosticId: CodecTypes['pg/text@1']['input'];
      readonly id: CodecTypes['pg/text@1']['input'];
      readonly inferredConfidence: CodecTypes['pg/text@1']['input'];
      readonly inferredMasterySignal: CodecTypes['pg/text@1']['input'];
      readonly interventionId: CodecTypes['pg/text@1']['input'] | null;
      readonly purpose: CodecTypes['pg/text@1']['input'];
      readonly questionId: CodecTypes['pg/text@1']['input'];
      readonly responseTimeSeconds: CodecTypes['pg/int4@1']['input'];
      readonly selectedOption: CodecTypes['pg/text@1']['input'] | null;
      readonly studentId: CodecTypes['pg/text@1']['input'];
      readonly telemetryJson: CodecTypes['pg/text@1']['input'];
    };
    readonly diagnosticSession: {
      readonly completedAt: CodecTypes['pg/text@1']['input'] | null;
      readonly completedInSeconds: CodecTypes['pg/int4@1']['input'] | null;
      readonly id: CodecTypes['pg/text@1']['input'];
      readonly startedAt: CodecTypes['pg/text@1']['input'];
      readonly studentId: CodecTypes['pg/text@1']['input'];
      readonly subject: CodecTypes['pg/text@1']['input'];
    };
    readonly intervention: {
      readonly actionType: CodecTypes['pg/text@1']['input'];
      readonly completedAt: CodecTypes['pg/text@1']['input'] | null;
      readonly contentJson: CodecTypes['pg/text@1']['input'];
      readonly id: CodecTypes['pg/text@1']['input'];
      readonly improved: CodecTypes['pg/int4@1']['input'] | null;
      readonly masteryAfter: CodecTypes['pg/float8@1']['input'] | null;
      readonly masteryBefore: CodecTypes['pg/float8@1']['input'];
      readonly startedAt: CodecTypes['pg/text@1']['input'];
      readonly studentId: CodecTypes['pg/text@1']['input'];
      readonly topic: CodecTypes['pg/text@1']['input'];
    };
    readonly learnerProfile: {
      readonly byTopicJson: CodecTypes['pg/text@1']['input'];
      readonly headlineDiagnosisJson: CodecTypes['pg/text@1']['input'] | null;
      readonly id: CodecTypes['pg/text@1']['input'];
      readonly overallJson: CodecTypes['pg/text@1']['input'];
      readonly profileConfidence: CodecTypes['pg/float8@1']['input'];
      readonly readinessIndex: CodecTypes['pg/int4@1']['input'];
      readonly studentId: CodecTypes['pg/text@1']['input'];
      readonly updatedAt: CodecTypes['pg/text@1']['input'];
    };
    readonly student: {
      readonly createdAt: CodecTypes['pg/text@1']['input'];
      readonly id: CodecTypes['pg/text@1']['input'];
      readonly name: CodecTypes['pg/text@1']['input'] | null;
      readonly subjects: CodecTypes['pg/text@1']['input'];
      readonly targetExam: CodecTypes['pg/text@1']['input'];
      readonly targetScore: CodecTypes['pg/int4@1']['input'];
    };
  };
};

export namespace Models {
  export type public_Student = {
    id: CodecTypes['pg/text@1']['output'];
    name: CodecTypes['pg/text@1']['output'] | null;
    targetExam: CodecTypes['pg/text@1']['output'];
    targetScore: CodecTypes['pg/int4@1']['output'];
    subjects: CodecTypes['pg/text@1']['output'];
    createdAt: CodecTypes['pg/text@1']['output'];
    attempts: public_Attempt[];
    interventions: public_Intervention[];
    profile: public_LearnerProfile | null;
    sessions: public_DiagnosticSession[];
    readonly [RelationKeys]?: 'attempts' | 'interventions' | 'profile' | 'sessions';
  };
  export type public_DiagnosticSession = {
    id: CodecTypes['pg/text@1']['output'];
    studentId: CodecTypes['pg/text@1']['output'];
    subject: CodecTypes['pg/text@1']['output'];
    startedAt: CodecTypes['pg/text@1']['output'];
    completedAt: CodecTypes['pg/text@1']['output'] | null;
    completedInSeconds: CodecTypes['pg/int4@1']['output'] | null;
    attempts: public_Attempt[];
    student: public_Student;
    readonly [RelationKeys]?: 'attempts' | 'student';
  };
  export type public_Attempt = {
    id: CodecTypes['pg/text@1']['output'];
    studentId: CodecTypes['pg/text@1']['output'];
    diagnosticId: CodecTypes['pg/text@1']['output'];
    interventionId: CodecTypes['pg/text@1']['output'] | null;
    questionId: CodecTypes['pg/text@1']['output'];
    purpose: CodecTypes['pg/text@1']['output'];
    selectedOption: CodecTypes['pg/text@1']['output'] | null;
    correct: CodecTypes['pg/int4@1']['output'];
    responseTimeSeconds: CodecTypes['pg/int4@1']['output'];
    inferredConfidence: CodecTypes['pg/text@1']['output'];
    inferredMasterySignal: CodecTypes['pg/text@1']['output'];
    telemetryJson: CodecTypes['pg/text@1']['output'];
    diagnosisJson: CodecTypes['pg/text@1']['output'] | null;
    createdAt: CodecTypes['pg/text@1']['output'];
    session: public_DiagnosticSession;
    student: public_Student;
    readonly [RelationKeys]?: 'session' | 'student';
  };
  export type public_LearnerProfile = {
    id: CodecTypes['pg/text@1']['output'];
    studentId: CodecTypes['pg/text@1']['output'];
    overallJson: CodecTypes['pg/text@1']['output'];
    byTopicJson: CodecTypes['pg/text@1']['output'];
    headlineDiagnosisJson: CodecTypes['pg/text@1']['output'] | null;
    readinessIndex: CodecTypes['pg/int4@1']['output'];
    profileConfidence: CodecTypes['pg/float8@1']['output'];
    updatedAt: CodecTypes['pg/text@1']['output'];
    student: public_Student;
    readonly [RelationKeys]?: 'student';
  };
  export type public_Intervention = {
    id: CodecTypes['pg/text@1']['output'];
    studentId: CodecTypes['pg/text@1']['output'];
    topic: CodecTypes['pg/text@1']['output'];
    actionType: CodecTypes['pg/text@1']['output'];
    contentJson: CodecTypes['pg/text@1']['output'];
    startedAt: CodecTypes['pg/text@1']['output'];
    completedAt: CodecTypes['pg/text@1']['output'] | null;
    masteryBefore: CodecTypes['pg/float8@1']['output'];
    masteryAfter: CodecTypes['pg/float8@1']['output'] | null;
    improved: CodecTypes['pg/int4@1']['output'] | null;
    student: public_Student;
    readonly [RelationKeys]?: 'student';
  };
}

export declare const models: {
  public: {
    Student: Models.public_Student;
    DiagnosticSession: Models.public_DiagnosticSession;
    Attempt: Models.public_Attempt;
    LearnerProfile: Models.public_LearnerProfile;
    Intervention: Models.public_Intervention;
  };
};

export type TypeMaps = TypeMapsType<
  CodecTypes,
  QueryOperationTypes,
  FieldOutputTypes,
  FieldInputTypes,
  StorageColumnTypes,
  StorageColumnInputTypes,
  AggregateTypes
>;

type ContractBase = Omit<
  ContractType<{
    readonly namespaces: {
      readonly public: {
        readonly id: 'public';
        readonly kind: 'postgres-schema';
        readonly entries: {
          readonly table: {
            readonly attempt: {
              columns: {
                readonly id: {
                  readonly nativeType: 'text';
                  readonly codecId: 'pg/text@1';
                  readonly nullable: false;
                };
                readonly studentId: {
                  readonly nativeType: 'text';
                  readonly codecId: 'pg/text@1';
                  readonly nullable: false;
                };
                readonly diagnosticId: {
                  readonly nativeType: 'text';
                  readonly codecId: 'pg/text@1';
                  readonly nullable: false;
                };
                readonly interventionId: {
                  readonly nativeType: 'text';
                  readonly codecId: 'pg/text@1';
                  readonly nullable: true;
                };
                readonly questionId: {
                  readonly nativeType: 'text';
                  readonly codecId: 'pg/text@1';
                  readonly nullable: false;
                };
                readonly purpose: {
                  readonly nativeType: 'text';
                  readonly codecId: 'pg/text@1';
                  readonly nullable: false;
                };
                readonly selectedOption: {
                  readonly nativeType: 'text';
                  readonly codecId: 'pg/text@1';
                  readonly nullable: true;
                };
                readonly correct: {
                  readonly nativeType: 'int4';
                  readonly codecId: 'pg/int4@1';
                  readonly nullable: false;
                };
                readonly responseTimeSeconds: {
                  readonly nativeType: 'int4';
                  readonly codecId: 'pg/int4@1';
                  readonly nullable: false;
                };
                readonly inferredConfidence: {
                  readonly nativeType: 'text';
                  readonly codecId: 'pg/text@1';
                  readonly nullable: false;
                };
                readonly inferredMasterySignal: {
                  readonly nativeType: 'text';
                  readonly codecId: 'pg/text@1';
                  readonly nullable: false;
                };
                readonly telemetryJson: {
                  readonly nativeType: 'text';
                  readonly codecId: 'pg/text@1';
                  readonly nullable: false;
                };
                readonly diagnosisJson: {
                  readonly nativeType: 'text';
                  readonly codecId: 'pg/text@1';
                  readonly nullable: true;
                };
                readonly createdAt: {
                  readonly nativeType: 'text';
                  readonly codecId: 'pg/text@1';
                  readonly nullable: false;
                };
              };
              primaryKey: { readonly columns: readonly ['id'] };
              uniques: readonly [];
              indexes: readonly [
                {
                  readonly name: 'attempt_studentId_idx_bf255322';
                  readonly prefix: 'attempt_studentId_idx';
                  readonly columns: readonly ['studentId'];
                  readonly unique: false;
                },
                {
                  readonly name: 'attempt_diagnosticId_idx_928861a5';
                  readonly prefix: 'attempt_diagnosticId_idx';
                  readonly columns: readonly ['diagnosticId'];
                  readonly unique: false;
                },
              ];
              foreignKeys: readonly [
                {
                  readonly source: {
                    readonly namespaceId: 'public' & NamespaceId;
                    readonly tableName: 'attempt';
                    readonly columns: readonly ['studentId'];
                  };
                  readonly target: {
                    readonly namespaceId: 'public' & NamespaceId;
                    readonly tableName: 'student';
                    readonly columns: readonly ['id'];
                  };
                },
                {
                  readonly source: {
                    readonly namespaceId: 'public' & NamespaceId;
                    readonly tableName: 'attempt';
                    readonly columns: readonly ['diagnosticId'];
                  };
                  readonly target: {
                    readonly namespaceId: 'public' & NamespaceId;
                    readonly tableName: 'diagnosticSession';
                    readonly columns: readonly ['id'];
                  };
                },
              ];
            };
            readonly diagnosticSession: {
              columns: {
                readonly id: {
                  readonly nativeType: 'text';
                  readonly codecId: 'pg/text@1';
                  readonly nullable: false;
                };
                readonly studentId: {
                  readonly nativeType: 'text';
                  readonly codecId: 'pg/text@1';
                  readonly nullable: false;
                };
                readonly subject: {
                  readonly nativeType: 'text';
                  readonly codecId: 'pg/text@1';
                  readonly nullable: false;
                };
                readonly startedAt: {
                  readonly nativeType: 'text';
                  readonly codecId: 'pg/text@1';
                  readonly nullable: false;
                };
                readonly completedAt: {
                  readonly nativeType: 'text';
                  readonly codecId: 'pg/text@1';
                  readonly nullable: true;
                };
                readonly completedInSeconds: {
                  readonly nativeType: 'int4';
                  readonly codecId: 'pg/int4@1';
                  readonly nullable: true;
                };
              };
              primaryKey: { readonly columns: readonly ['id'] };
              uniques: readonly [];
              indexes: readonly [
                {
                  readonly name: 'diagnosticSession_studentId_idx_bf255322';
                  readonly prefix: 'diagnosticSession_studentId_idx';
                  readonly columns: readonly ['studentId'];
                  readonly unique: false;
                },
              ];
              foreignKeys: readonly [
                {
                  readonly source: {
                    readonly namespaceId: 'public' & NamespaceId;
                    readonly tableName: 'diagnosticSession';
                    readonly columns: readonly ['studentId'];
                  };
                  readonly target: {
                    readonly namespaceId: 'public' & NamespaceId;
                    readonly tableName: 'student';
                    readonly columns: readonly ['id'];
                  };
                },
              ];
            };
            readonly intervention: {
              columns: {
                readonly id: {
                  readonly nativeType: 'text';
                  readonly codecId: 'pg/text@1';
                  readonly nullable: false;
                };
                readonly studentId: {
                  readonly nativeType: 'text';
                  readonly codecId: 'pg/text@1';
                  readonly nullable: false;
                };
                readonly topic: {
                  readonly nativeType: 'text';
                  readonly codecId: 'pg/text@1';
                  readonly nullable: false;
                };
                readonly actionType: {
                  readonly nativeType: 'text';
                  readonly codecId: 'pg/text@1';
                  readonly nullable: false;
                };
                readonly contentJson: {
                  readonly nativeType: 'text';
                  readonly codecId: 'pg/text@1';
                  readonly nullable: false;
                };
                readonly startedAt: {
                  readonly nativeType: 'text';
                  readonly codecId: 'pg/text@1';
                  readonly nullable: false;
                };
                readonly completedAt: {
                  readonly nativeType: 'text';
                  readonly codecId: 'pg/text@1';
                  readonly nullable: true;
                };
                readonly masteryBefore: {
                  readonly nativeType: 'float8';
                  readonly codecId: 'pg/float8@1';
                  readonly nullable: false;
                };
                readonly masteryAfter: {
                  readonly nativeType: 'float8';
                  readonly codecId: 'pg/float8@1';
                  readonly nullable: true;
                };
                readonly improved: {
                  readonly nativeType: 'int4';
                  readonly codecId: 'pg/int4@1';
                  readonly nullable: true;
                };
              };
              primaryKey: { readonly columns: readonly ['id'] };
              uniques: readonly [];
              indexes: readonly [
                {
                  readonly name: 'intervention_studentId_idx_bf255322';
                  readonly prefix: 'intervention_studentId_idx';
                  readonly columns: readonly ['studentId'];
                  readonly unique: false;
                },
              ];
              foreignKeys: readonly [
                {
                  readonly source: {
                    readonly namespaceId: 'public' & NamespaceId;
                    readonly tableName: 'intervention';
                    readonly columns: readonly ['studentId'];
                  };
                  readonly target: {
                    readonly namespaceId: 'public' & NamespaceId;
                    readonly tableName: 'student';
                    readonly columns: readonly ['id'];
                  };
                },
              ];
            };
            readonly learnerProfile: {
              columns: {
                readonly id: {
                  readonly nativeType: 'text';
                  readonly codecId: 'pg/text@1';
                  readonly nullable: false;
                };
                readonly studentId: {
                  readonly nativeType: 'text';
                  readonly codecId: 'pg/text@1';
                  readonly nullable: false;
                };
                readonly overallJson: {
                  readonly nativeType: 'text';
                  readonly codecId: 'pg/text@1';
                  readonly nullable: false;
                };
                readonly byTopicJson: {
                  readonly nativeType: 'text';
                  readonly codecId: 'pg/text@1';
                  readonly nullable: false;
                };
                readonly headlineDiagnosisJson: {
                  readonly nativeType: 'text';
                  readonly codecId: 'pg/text@1';
                  readonly nullable: true;
                };
                readonly readinessIndex: {
                  readonly nativeType: 'int4';
                  readonly codecId: 'pg/int4@1';
                  readonly nullable: false;
                };
                readonly profileConfidence: {
                  readonly nativeType: 'float8';
                  readonly codecId: 'pg/float8@1';
                  readonly nullable: false;
                };
                readonly updatedAt: {
                  readonly nativeType: 'text';
                  readonly codecId: 'pg/text@1';
                  readonly nullable: false;
                };
              };
              primaryKey: { readonly columns: readonly ['id'] };
              uniques: readonly [{ readonly columns: readonly ['studentId'] }];
              indexes: readonly [];
              foreignKeys: readonly [
                {
                  readonly source: {
                    readonly namespaceId: 'public' & NamespaceId;
                    readonly tableName: 'learnerProfile';
                    readonly columns: readonly ['studentId'];
                  };
                  readonly target: {
                    readonly namespaceId: 'public' & NamespaceId;
                    readonly tableName: 'student';
                    readonly columns: readonly ['id'];
                  };
                },
              ];
            };
            readonly student: {
              columns: {
                readonly id: {
                  readonly nativeType: 'text';
                  readonly codecId: 'pg/text@1';
                  readonly nullable: false;
                };
                readonly name: {
                  readonly nativeType: 'text';
                  readonly codecId: 'pg/text@1';
                  readonly nullable: true;
                };
                readonly targetExam: {
                  readonly nativeType: 'text';
                  readonly codecId: 'pg/text@1';
                  readonly nullable: false;
                  readonly default: {
                    readonly kind: 'literal';
                    readonly value: DefaultLiteralValue<'pg/text@1', 'JAMB'>;
                  };
                };
                readonly targetScore: {
                  readonly nativeType: 'int4';
                  readonly codecId: 'pg/int4@1';
                  readonly nullable: false;
                };
                readonly subjects: {
                  readonly nativeType: 'text';
                  readonly codecId: 'pg/text@1';
                  readonly nullable: false;
                };
                readonly createdAt: {
                  readonly nativeType: 'text';
                  readonly codecId: 'pg/text@1';
                  readonly nullable: false;
                };
              };
              primaryKey: { readonly columns: readonly ['id'] };
              uniques: readonly [];
              indexes: readonly [];
              foreignKeys: readonly [];
            };
          };
        };
      };
    };
    readonly storageHash: StorageHash;
  }>,
  'roots' | 'domain'
> & {
  readonly target: 'postgres';
  readonly targetFamily: 'sql';
  readonly roots: {
    readonly student: { readonly namespace: 'public' & NamespaceId; readonly model: 'Student' };
    readonly diagnosticSession: {
      readonly namespace: 'public' & NamespaceId;
      readonly model: 'DiagnosticSession';
    };
    readonly attempt: { readonly namespace: 'public' & NamespaceId; readonly model: 'Attempt' };
    readonly learnerProfile: {
      readonly namespace: 'public' & NamespaceId;
      readonly model: 'LearnerProfile';
    };
    readonly intervention: {
      readonly namespace: 'public' & NamespaceId;
      readonly model: 'Intervention';
    };
  };
  readonly domain: {
    readonly namespaces: {
      readonly public: {
        readonly models: {
          readonly Attempt: {
            readonly fields: {
              readonly id: {
                readonly nullable: false;
                readonly type: { readonly kind: 'scalar'; readonly codecId: 'pg/text@1' };
              };
              readonly studentId: {
                readonly nullable: false;
                readonly type: { readonly kind: 'scalar'; readonly codecId: 'pg/text@1' };
              };
              readonly diagnosticId: {
                readonly nullable: false;
                readonly type: { readonly kind: 'scalar'; readonly codecId: 'pg/text@1' };
              };
              readonly interventionId: {
                readonly nullable: true;
                readonly type: { readonly kind: 'scalar'; readonly codecId: 'pg/text@1' };
              };
              readonly questionId: {
                readonly nullable: false;
                readonly type: { readonly kind: 'scalar'; readonly codecId: 'pg/text@1' };
              };
              readonly purpose: {
                readonly nullable: false;
                readonly type: { readonly kind: 'scalar'; readonly codecId: 'pg/text@1' };
              };
              readonly selectedOption: {
                readonly nullable: true;
                readonly type: { readonly kind: 'scalar'; readonly codecId: 'pg/text@1' };
              };
              readonly correct: {
                readonly nullable: false;
                readonly type: { readonly kind: 'scalar'; readonly codecId: 'pg/int4@1' };
              };
              readonly responseTimeSeconds: {
                readonly nullable: false;
                readonly type: { readonly kind: 'scalar'; readonly codecId: 'pg/int4@1' };
              };
              readonly inferredConfidence: {
                readonly nullable: false;
                readonly type: { readonly kind: 'scalar'; readonly codecId: 'pg/text@1' };
              };
              readonly inferredMasterySignal: {
                readonly nullable: false;
                readonly type: { readonly kind: 'scalar'; readonly codecId: 'pg/text@1' };
              };
              readonly telemetryJson: {
                readonly nullable: false;
                readonly type: { readonly kind: 'scalar'; readonly codecId: 'pg/text@1' };
              };
              readonly diagnosisJson: {
                readonly nullable: true;
                readonly type: { readonly kind: 'scalar'; readonly codecId: 'pg/text@1' };
              };
              readonly createdAt: {
                readonly nullable: false;
                readonly type: { readonly kind: 'scalar'; readonly codecId: 'pg/text@1' };
              };
            };
            readonly relations: {
              readonly session: {
                readonly to: {
                  readonly namespace: 'public' & NamespaceId;
                  readonly model: 'DiagnosticSession';
                };
                readonly cardinality: 'N:1';
                readonly nullable: false;
                readonly on: {
                  readonly localFields: readonly ['diagnosticId'];
                  readonly targetFields: readonly ['id'];
                };
              };
              readonly student: {
                readonly to: {
                  readonly namespace: 'public' & NamespaceId;
                  readonly model: 'Student';
                };
                readonly cardinality: 'N:1';
                readonly nullable: false;
                readonly on: {
                  readonly localFields: readonly ['studentId'];
                  readonly targetFields: readonly ['id'];
                };
              };
            };
            readonly storage: {
              readonly table: 'attempt';
              readonly namespaceId: 'public';
              readonly fields: {
                readonly id: { readonly column: 'id' };
                readonly studentId: { readonly column: 'studentId' };
                readonly diagnosticId: { readonly column: 'diagnosticId' };
                readonly interventionId: { readonly column: 'interventionId' };
                readonly questionId: { readonly column: 'questionId' };
                readonly purpose: { readonly column: 'purpose' };
                readonly selectedOption: { readonly column: 'selectedOption' };
                readonly correct: { readonly column: 'correct' };
                readonly responseTimeSeconds: { readonly column: 'responseTimeSeconds' };
                readonly inferredConfidence: { readonly column: 'inferredConfidence' };
                readonly inferredMasterySignal: { readonly column: 'inferredMasterySignal' };
                readonly telemetryJson: { readonly column: 'telemetryJson' };
                readonly diagnosisJson: { readonly column: 'diagnosisJson' };
                readonly createdAt: { readonly column: 'createdAt' };
              };
            };
          };
          readonly DiagnosticSession: {
            readonly fields: {
              readonly id: {
                readonly nullable: false;
                readonly type: { readonly kind: 'scalar'; readonly codecId: 'pg/text@1' };
              };
              readonly studentId: {
                readonly nullable: false;
                readonly type: { readonly kind: 'scalar'; readonly codecId: 'pg/text@1' };
              };
              readonly subject: {
                readonly nullable: false;
                readonly type: { readonly kind: 'scalar'; readonly codecId: 'pg/text@1' };
              };
              readonly startedAt: {
                readonly nullable: false;
                readonly type: { readonly kind: 'scalar'; readonly codecId: 'pg/text@1' };
              };
              readonly completedAt: {
                readonly nullable: true;
                readonly type: { readonly kind: 'scalar'; readonly codecId: 'pg/text@1' };
              };
              readonly completedInSeconds: {
                readonly nullable: true;
                readonly type: { readonly kind: 'scalar'; readonly codecId: 'pg/int4@1' };
              };
            };
            readonly relations: {
              readonly attempts: {
                readonly to: {
                  readonly namespace: 'public' & NamespaceId;
                  readonly model: 'Attempt';
                };
                readonly cardinality: '1:N';
                readonly on: {
                  readonly localFields: readonly ['id'];
                  readonly targetFields: readonly ['diagnosticId'];
                };
              };
              readonly student: {
                readonly to: {
                  readonly namespace: 'public' & NamespaceId;
                  readonly model: 'Student';
                };
                readonly cardinality: 'N:1';
                readonly nullable: false;
                readonly on: {
                  readonly localFields: readonly ['studentId'];
                  readonly targetFields: readonly ['id'];
                };
              };
            };
            readonly storage: {
              readonly table: 'diagnosticSession';
              readonly namespaceId: 'public';
              readonly fields: {
                readonly id: { readonly column: 'id' };
                readonly studentId: { readonly column: 'studentId' };
                readonly subject: { readonly column: 'subject' };
                readonly startedAt: { readonly column: 'startedAt' };
                readonly completedAt: { readonly column: 'completedAt' };
                readonly completedInSeconds: { readonly column: 'completedInSeconds' };
              };
            };
          };
          readonly Intervention: {
            readonly fields: {
              readonly id: {
                readonly nullable: false;
                readonly type: { readonly kind: 'scalar'; readonly codecId: 'pg/text@1' };
              };
              readonly studentId: {
                readonly nullable: false;
                readonly type: { readonly kind: 'scalar'; readonly codecId: 'pg/text@1' };
              };
              readonly topic: {
                readonly nullable: false;
                readonly type: { readonly kind: 'scalar'; readonly codecId: 'pg/text@1' };
              };
              readonly actionType: {
                readonly nullable: false;
                readonly type: { readonly kind: 'scalar'; readonly codecId: 'pg/text@1' };
              };
              readonly contentJson: {
                readonly nullable: false;
                readonly type: { readonly kind: 'scalar'; readonly codecId: 'pg/text@1' };
              };
              readonly startedAt: {
                readonly nullable: false;
                readonly type: { readonly kind: 'scalar'; readonly codecId: 'pg/text@1' };
              };
              readonly completedAt: {
                readonly nullable: true;
                readonly type: { readonly kind: 'scalar'; readonly codecId: 'pg/text@1' };
              };
              readonly masteryBefore: {
                readonly nullable: false;
                readonly type: { readonly kind: 'scalar'; readonly codecId: 'pg/float8@1' };
              };
              readonly masteryAfter: {
                readonly nullable: true;
                readonly type: { readonly kind: 'scalar'; readonly codecId: 'pg/float8@1' };
              };
              readonly improved: {
                readonly nullable: true;
                readonly type: { readonly kind: 'scalar'; readonly codecId: 'pg/int4@1' };
              };
            };
            readonly relations: {
              readonly student: {
                readonly to: {
                  readonly namespace: 'public' & NamespaceId;
                  readonly model: 'Student';
                };
                readonly cardinality: 'N:1';
                readonly nullable: false;
                readonly on: {
                  readonly localFields: readonly ['studentId'];
                  readonly targetFields: readonly ['id'];
                };
              };
            };
            readonly storage: {
              readonly table: 'intervention';
              readonly namespaceId: 'public';
              readonly fields: {
                readonly id: { readonly column: 'id' };
                readonly studentId: { readonly column: 'studentId' };
                readonly topic: { readonly column: 'topic' };
                readonly actionType: { readonly column: 'actionType' };
                readonly contentJson: { readonly column: 'contentJson' };
                readonly startedAt: { readonly column: 'startedAt' };
                readonly completedAt: { readonly column: 'completedAt' };
                readonly masteryBefore: { readonly column: 'masteryBefore' };
                readonly masteryAfter: { readonly column: 'masteryAfter' };
                readonly improved: { readonly column: 'improved' };
              };
            };
          };
          readonly LearnerProfile: {
            readonly fields: {
              readonly id: {
                readonly nullable: false;
                readonly type: { readonly kind: 'scalar'; readonly codecId: 'pg/text@1' };
              };
              readonly studentId: {
                readonly nullable: false;
                readonly type: { readonly kind: 'scalar'; readonly codecId: 'pg/text@1' };
              };
              readonly overallJson: {
                readonly nullable: false;
                readonly type: { readonly kind: 'scalar'; readonly codecId: 'pg/text@1' };
              };
              readonly byTopicJson: {
                readonly nullable: false;
                readonly type: { readonly kind: 'scalar'; readonly codecId: 'pg/text@1' };
              };
              readonly headlineDiagnosisJson: {
                readonly nullable: true;
                readonly type: { readonly kind: 'scalar'; readonly codecId: 'pg/text@1' };
              };
              readonly readinessIndex: {
                readonly nullable: false;
                readonly type: { readonly kind: 'scalar'; readonly codecId: 'pg/int4@1' };
              };
              readonly profileConfidence: {
                readonly nullable: false;
                readonly type: { readonly kind: 'scalar'; readonly codecId: 'pg/float8@1' };
              };
              readonly updatedAt: {
                readonly nullable: false;
                readonly type: { readonly kind: 'scalar'; readonly codecId: 'pg/text@1' };
              };
            };
            readonly relations: {
              readonly student: {
                readonly to: {
                  readonly namespace: 'public' & NamespaceId;
                  readonly model: 'Student';
                };
                readonly cardinality: 'N:1';
                readonly nullable: false;
                readonly on: {
                  readonly localFields: readonly ['studentId'];
                  readonly targetFields: readonly ['id'];
                };
              };
            };
            readonly storage: {
              readonly table: 'learnerProfile';
              readonly namespaceId: 'public';
              readonly fields: {
                readonly id: { readonly column: 'id' };
                readonly studentId: { readonly column: 'studentId' };
                readonly overallJson: { readonly column: 'overallJson' };
                readonly byTopicJson: { readonly column: 'byTopicJson' };
                readonly headlineDiagnosisJson: { readonly column: 'headlineDiagnosisJson' };
                readonly readinessIndex: { readonly column: 'readinessIndex' };
                readonly profileConfidence: { readonly column: 'profileConfidence' };
                readonly updatedAt: { readonly column: 'updatedAt' };
              };
            };
          };
          readonly Student: {
            readonly fields: {
              readonly id: {
                readonly nullable: false;
                readonly type: { readonly kind: 'scalar'; readonly codecId: 'pg/text@1' };
              };
              readonly name: {
                readonly nullable: true;
                readonly type: { readonly kind: 'scalar'; readonly codecId: 'pg/text@1' };
              };
              readonly targetExam: {
                readonly nullable: false;
                readonly type: { readonly kind: 'scalar'; readonly codecId: 'pg/text@1' };
              };
              readonly targetScore: {
                readonly nullable: false;
                readonly type: { readonly kind: 'scalar'; readonly codecId: 'pg/int4@1' };
              };
              readonly subjects: {
                readonly nullable: false;
                readonly type: { readonly kind: 'scalar'; readonly codecId: 'pg/text@1' };
              };
              readonly createdAt: {
                readonly nullable: false;
                readonly type: { readonly kind: 'scalar'; readonly codecId: 'pg/text@1' };
              };
            };
            readonly relations: {
              readonly attempts: {
                readonly to: {
                  readonly namespace: 'public' & NamespaceId;
                  readonly model: 'Attempt';
                };
                readonly cardinality: '1:N';
                readonly on: {
                  readonly localFields: readonly ['id'];
                  readonly targetFields: readonly ['studentId'];
                };
              };
              readonly interventions: {
                readonly to: {
                  readonly namespace: 'public' & NamespaceId;
                  readonly model: 'Intervention';
                };
                readonly cardinality: '1:N';
                readonly on: {
                  readonly localFields: readonly ['id'];
                  readonly targetFields: readonly ['studentId'];
                };
              };
              readonly profile: {
                readonly to: {
                  readonly namespace: 'public' & NamespaceId;
                  readonly model: 'LearnerProfile';
                };
                readonly cardinality: '1:1';
                readonly nullable: true;
                readonly on: {
                  readonly localFields: readonly ['id'];
                  readonly targetFields: readonly ['studentId'];
                };
              };
              readonly sessions: {
                readonly to: {
                  readonly namespace: 'public' & NamespaceId;
                  readonly model: 'DiagnosticSession';
                };
                readonly cardinality: '1:N';
                readonly on: {
                  readonly localFields: readonly ['id'];
                  readonly targetFields: readonly ['studentId'];
                };
              };
            };
            readonly storage: {
              readonly table: 'student';
              readonly namespaceId: 'public';
              readonly fields: {
                readonly id: { readonly column: 'id' };
                readonly name: { readonly column: 'name' };
                readonly targetExam: { readonly column: 'targetExam' };
                readonly targetScore: { readonly column: 'targetScore' };
                readonly subjects: { readonly column: 'subjects' };
                readonly createdAt: { readonly column: 'createdAt' };
              };
            };
          };
        };
      };
    };
  };
  readonly capabilities: {
    readonly postgres: {
      readonly distinctOn: true;
      readonly jsonAgg: true;
      readonly lateral: true;
      readonly limit: true;
      readonly orderBy: true;
      readonly returning: true;
    };
    readonly sql: {
      readonly checkConstraint: true;
      readonly defaultInInsert: true;
      readonly enums: true;
      readonly lateral: true;
      readonly returning: true;
      readonly scalarList: true;
    };
  };
  readonly extensions: {};
  readonly meta: {};

  readonly profileHash: ProfileHash;
};

export type Contract = ContractWithTypeMaps<ContractBase, TypeMaps>;

export type Namespaces = Contract['storage']['namespaces'];
